### ISSUE TITLE
[Question] I want to exec multiple command in ssh

### ISSUE THREAD

**Issue by abdrozak20** [mscdex/ssh2#1001]
Hi all,
I want to make multiple command in ssh like this
![image](https://user-images.githubusercontent.com/33420123/115179713-22bed080-a0fe-11eb-96e9-39e8016d832b.png)

and i try using this package
![image](https://user-images.githubusercontent.com/33420123/115179845-729d9780-a0fe-11eb-9241-44fba307a768.png)

but it's not works.
Any idea ? Please help me

**Comment by theophilusx** [comment]
FYI the node-ssh package is not the same as the package from this
repository. This repository is for the ssh2 package, a dependency of
the node-ssh package.

You would be better logging this issue against the node-ssh repository
or try implementing your functionality just using the ssh2 package
(which is event based rather than Promise based).


-- 
Tim Cross

**Comment by mscdex** [comment]
You will need to file this issue with the `node-ssh` maintainers instead.
