### ISSUE TITLE
SFTP Readdir Method

### ISSUE THREAD

**Issue by rabeeshcharles** [mscdex/ssh2#1036]
My need is like filtering the Files From the  FTP Folder, So How Can i Achieve that?
![image](https://user-images.githubusercontent.com/30102705/125783257-609999fe-e5cb-48e7-8d51-963d66ea4248.png)

**Comment by rabeeshcharles** [comment]
Kindly suggest some ideas to filter only the files from the readdir result which contains both file and folder names.

**Comment by theophilusx** [comment]
Have a look at https://github.com/theophilusx/ssh2-sftp-client/src/index.js for some examples of doing this (and other things) with ssh2 and sftp. While the module wraps things in a Promise API, it is just normal ssh2 calls inside. In particular, look at the code for the list() method to get an idea of how you can filter output from readdir call.

**Comment by rabeeshcharles** [comment]
Yes. I swa it, but the list method is belongs to another npm call ssh2-sftp-client npm..but I have used only ssh2 npm due to the popularity....so is there any other logic within the ssh2 npm to achieve the requirement..

**Comment by theophilusx** [comment]
I'm not sure you understood what I meant.

The ssh2-sftp-client uses ssh2 to perform all the sftp interaction. All it does
is wrap those calls inside Promises to provide a Promise based API version.
Under the hood, it is just ssh2. What I meant was that if you look at the code
which implements the list() method in ssh2-sftp-client, you can see how to
implement readdir and filter the responses. Basically, you can use the
ssh2-sftp-client code as an example of how you can use ssh2's API.

There is no specific logic built into ssh2 to filter the results. You need to do
this in your code by filtering the data returned from the readdir call. This is
trivial to do as readdir will return an array of objects. You just need to use
the Array.filter() method to generate a new array of result objects based on the
object.filename property which satisfy your requirements.

Regards,

Tim

--
*Tim Cross*

/For gor sake stop laughing, this is serious!/

**Comment by rabeeshcharles** [comment]
ssh2-sftp-client - 5years - 1.55lak issues 4
------------------

reqSftp.list('FTP Path') Output
----------------------------------
[
  {
    type: '-',
    name: 'MicrosoftTeams-image (2).png',
    size: 263047,
    modifyTime: 1625063555000,
    accessTime: 1625063555000,
    rights: { user: 'rw', group: '***', other: '***' },
    owner: 0,
    group: 0
  }
] 




ssh2 - 9years - 9lak issues 45
----------------------------------
sftp.readdir() Output
----------------------------
[
  {
    filename: 'MicrosoftTeams-image (2).png',
    longname: '-rw-******    1 -        -          263047 Jun 30 20:02 MicrosoftTeams-image (2).png',
    attrs: Stats {
      mode: 33159,
      uid: 0,
      gid: 0,
      size: 263047,
      atime: 1625063555,
      mtime: 1625063555,
      extended: undefined
    }
  }
  }
]



=> Here In ssh2-sftp-client, it has a property called type as '-,d,l' right?...Based on this user can able to know like this is file or folder...
=> But In ssh2, There is no any property to find the informations right?..This is my doubt
=> By using the filename property we can filter it like file extension right?

**Comment by theophilusx** [comment]
All of the information returned by list() in ssh2-sftp-client is obtained from
the value returned by ssh2's readdir() method. The method returns an array of
objects where each object has the properties filename, longname, and attrs. The
attrs property is itself an object with properties mode, uid, gid, size, atime
and mtime.

All that ssh2-sftp-client does is take that array of objects and map it into a
new array of objects with properties for type, name, size, modifyTime,
accessTime, rights, owner and group. All of the information is determined by
what readdir returns.

For example, the type of the 'thing' is determined by looking at the first
character of the longname property. The longname property is sort of equivalent
to the command `ls -l' where the first character is the file type - a `-'
indicates a normal file, a `d' is a directory, an `l' is a symbolic link etc.
This is much safer than relying on file extensions because not all files have
extensions and some file types, like a symbolic link, do not have defined
extensions. You could have a file called /my-thing/, which could be a normal
file, a directory or a symbolic link. However, if it is a normal file, the
longname will have a `-' as the first character, if it is a directory it will
have `d' and if it is a symbolic link it would have `l'. For example, the
longname for some items could because

,----
| -rw-****** 1 - - 263047 Jun 30 20:02 some-thing
| drw-****** 1 - -     17 Jun 20 10:02 another-thing
| lrw-****** 1 - -   2304 Jun 15 22:12 third-thing
`----

In the above /some-thing/ is a normal file, /another-thing/ is a directory
(folder) and /third-thing/ is a symbolic link. Note that the exact format of the
longname output varies slightly depending on the underlying file system of the
remote sftp server. The format is derived from *nix systems where you have 3
distinct access groups, owner, group and other and you have 3 types of access
right, read, write and execute. Because MS filesystems don't have an equivalent
/mapping/ for group and other, the values are replaced by `*'.

To determine the type of an entry in the results returned by readdir(), ssh2-sftp-client just looks at the first character in the longname value e.g

,----
| type: item.longname.substr(0, 1),
`----

The above line just sets `type' to the value of the first character in the
`longname' property. Using the listing above, this would be `-' for
/some-thing/, `d' for /another-thing/ and `l' for /thrid-thing/.

As a basic example, if you wanted to get a listing which only included normal
files, you could do something like

,----
| client.readdir(remoePath, (err, listing) => {
|   if (err) {
|     console.error(err.message);
|     return null;
|   }
|   return listinjg.filter((entry) => entry.longname.substring(0, 1) === '-');
| })
`----

The above is untested, so may have bugs, but should give you the idea. The
 ~listing.filter() call is using the Array.filter() built-in method to generate
 a new array which only includes those elements (objects) in the original array
 which return true for the filter. The fileter is only going to be true for
 entries which have a longname property value that starts with `-'. Regards,

Tim

--
*Tim Cross*

/For gor sake stop laughing, this is serious!/
