### ISSUE TITLE
Error setting remote directory on SFTP-only server 

### ISSUE THREAD

**Issue by jatester** [mscdex/ssh2#1119]
When I try to connect with SFTP client to SFTP-only server I am getting error setting remote directory and I can't see folders and navigate.

How to set init remote directory when client connect after authentication?

**Comment by mscdex** [comment]
Are you sure you're using `ssh2` directly and not some other module that depends on it? `ssh2` does not automatically perform any actions when starting an SFTP session.

**Comment by jatester** [comment]
I am using an example for SFTP-only server

**Comment by theophilusx** [comment]
This is often determined by the server when you log in. Some sftp
server, like old ftp servers, don't allow clients to list/view
directories or contents (e.g. an anonymous sftp server which allows you
to upload a file, but does not allow you to see files uploaded by
others).

First think I would try is verify you can do what your trying to do
using just the openssh CLI client as it could be server permissions
which are preventing you from being able to set/create a remote
directory. If you can do it with openssh sftp cli, then we can look at
your code to see why it isn't working with ssh2. 

The other thing which can trip people up is that the remote server may
not be putting you into the directory you think it is, so commands to
set or create a new directory can fail because the remote path is not
correct. Can be a good idea to query the directory you are in after
connecting to verify it is the path you expect.

**Comment by mscdex** [comment]
Ah ok, so you're creating an SFTP *server* using `ssh2`.

The SFTP server example in the readme is not a complete implementation as it does not handle all of the possible SFTP requests for brevity. You can reference the [SFTP events documentation](https://github.com/mscdex/ssh2/blob/master/SFTP.md#sftp-events) at the possible server events you can listen for and handle as you wish.

**Comment by mscdex** [comment]
You should be able to set `debug: console.log` in your `ssh2.Server` configuration object to see debug output, which should include the requests being sent by the client.

**Comment by jatester** [comment]
@theophilusx @mscdex 
I could check the requested path using session.on('REALPATH') but how to callback to different path?

**Comment by theophilusx** [comment]
I misunderstood your original issue and didn't realise you were actually
implementing an sftp server.

The ssh2 library provides the basic infrastructure you need to receive
and reply to sftp requests. The rest is pretty much up to you as you
implement the server.

This means it is up to you to define how your server will interact with
the filepath and what that means for your clients. If you wanted to
write an sftp server which is similar to how sftp works in openssh, it
can get quite complex as you have to deal with OS level user permissions
and the OS level authentication infrastructure. This quickly becomes
complex and while it is doable, it is definitely a non-trivial bit of
coding.

An alternative I have used is to create a 'fake' virtual like file
system, which is essentially a bit of disk space owned by the sftp
server where the server manages access to the client through a thin
translation layer. The sftp server maps requests from the client onto
this fake filesystem and deals with mapping permissions and access etc.
Still a considerable amount of work, but far less complex than trying to
write a server which will provide access to a user's 'real' home
directory.

It really all depends on exactly what your trying to do and your
requirements. I've only written a fairly simple sftp server which I use
for testing and experiments (mainly as a testbed for developing sftp
clients). However, writing a full fledged sftp server, especially one
which gives OS level access to files and directories, is a big project
with lots of complexity.
