### ISSUE TITLE
Fix error handling of Node validation errors

### ISSUE THREAD

**Issue by GabrielLomba** [mscdex/ssh2#1132]
Whenever ```client.connect``` is called with invalid settings, the validation error is rethrown but the ```readyTimeout``` is not unset nor an ```error``` event is emitted. This behavior can be verified by running the script below:

```javascript
const {Client} = require('ssh2');

const main = async ()=>{
    const client = new Client();
    client.on('error', e=>console.log('event error: ', e));
    try {
        client.connect({
            host: '127.0.0.1',
            username: 'user',
            port: 288642,
        });
    } catch(e){ console.log('sync error: ', e.code, e); }
};

process.on('uncaughtException', (e, o)=>console.log('uncaught exception: ', e, o));

main();
```

**Expected behavior:**
Sync error and ```error``` event triggered with ERR_SOCKET_BAD_PORT and no timeout

**Observed behavior:**
Sync error triggered with ERR_SOCKET_BAD_PORT and the event loop waits until readyTimeout runs, when an ```error``` event is triggered with the unclear "Timed out while waiting for handshake").

This issue comes from the fact that we do not catch the error when calling [sock.connect](https://nodejs.org/api/net.html#socketconnect) in [this line](https://github.com/mscdex/ssh2/blob/master/lib/client.js#L1031). It would probably make sense to catch the error there, destroy the socket, clear the timeout, emit an ```error``` and rethrow the error. I'm willing to submit a PR for it.

For the record, this behavior also affects how [ssh2-sftp-client](https://www.npmjs.com/package/ssh2-sftp-client) handles these errors incorrectly.

**Comment by theophilusx** [comment]
Just a couple of points which might be worth noting.

- You don't need the async in your example. There is no async/await in
  ssh2.

- I don't think you can rely on try/catch when working with an event
based model as there is no guarantee an event will be fired before the
try/catch has completed.

- I think the issue you mentioned wrt ssh2-sftp-client is related, but
possibly more to do with the retry mechanism ssh2-sftp-client
implements. I'm looking into that now as I think ssh2-sftp-client should
be reporting the core error rather than the later timeout error.

I would agree that when a 'hard' unrecoverable error like
rangeError occurs, the connection should be ended and not wait for the
readyTimeout. At the same time, ssh2-sftp-client *should* see the
badRange error and should report it and force a connection end (if
possible), even if only to provide the client with a more accurate error
than a timeout error. For hard unrecoverable errors like this,
ssh2-sftp-client should short-circuit the retry mechanism as there is no
point in further retries after such an error.

**Comment by theophilusx** [comment]
Just a quick update for ssh2-sftp-client. I have modified the code which
does connection retry attempts so that it won't retry after a hard
unrecoverable error (such as port out of range, hostname lookup failure,
bad username etc). The updated code is on HEAD of ssh2-sftp-client
repository. This change means the correct error is now reported rather
than a generic timeout error.
