### ISSUE TITLE
Connection unresponsive

### ISSUE THREAD

**Issue by zhangbaojia** [mscdex/ssh2#1148]
No response for connection using version_ 1.0.0 or later,（The  version_0.8.9 can）。

**local system:**  windows10
**service system:**

![163130](https://user-images.githubusercontent.com/19427334/157620640-03da8ec5-2448-4905-8744-9dc3953f08c3.png)

**code snippet:**  version_ 1.7.0 'ready' does not enter

![163035](https://user-images.githubusercontent.com/19427334/157620644-869cf20f-63bb-46c0-8e4e-1e9c57b0a36d.png)

PS: Another service all succeeded。
![163210](https://user-images.githubusercontent.com/19427334/157620643-4398fe8a-3edc-4de7-9147-2b2e232d2eb5.png)

so , I What config should to do?

**Comment by mscdex** [comment]
What version of node is being used in both cases?

Also, what is the debug output (set `debug: console.log` in your `connect()` config object) for `ssh2` 1.7.0?

**Comment by zhangbaojia** [comment]
**node version_14.18.0**

![1091815](https://user-images.githubusercontent.com/19427334/157783236-d31f5c41-2f51-4189-a47b-dbd774ed3424.png)

**Comment by mscdex** [comment]
I don't see anything wrong in the debug output. The only thing similar to this that I've seen with modern branches of node (12.x and newer IIRC) is that some crypto operations can be very slow because of extra checks OpenSSL added to make sure various cryptographic algorithm parameters were "safe."

Usually you can tell if this is the case if one or more of the CPU cores used by the node process is pegged at 100% or close to that. The `readyTimeout` connection option can be increased from the default of 20 seconds to help workaround this, but if you're using the exact same node version in both scenarios, then that's probably not it and I'm not sure what to suggest, unless there is something blocking the traffic (you could probably check this with a tool like Wireshark to see if the server is sending a response to the KEXECDH_INIT that is the last thing to be sent).

**Comment by zhangbaojia** [comment]
**ssh2 version_0.8.9**[[successful](javascript:;)]

![4fc2e9de8ee8e3c4e820fd40f0318b1](https://user-images.githubusercontent.com/19427334/157830969-0ece159a-334a-4539-b3ad-cdf37038fd4e.png)

**ssh2 version_1.7.0**[[fail](javascript:;)]
![21ee8f650e099e027ef443f1cc63c48](https://user-images.githubusercontent.com/19427334/157830975-095db2f2-2003-4709-a80b-0350ea7e3fa5.png)

**OpenSSH** version:
![20220311163351](https://user-images.githubusercontent.com/19427334/157831704-3b3d0622-92b4-49dd-b83f-8f09a16be978.png)

**Comment by zhangbaojia** [comment]
This is the listening output for both versions of the connection.

**Comment by lwqysu** [comment]
The wrong case seems to be this ,the socket connection is closed without waiting for the client to send the Diffie-Hellman Key Exchange Init.
Don't know how to solve this problem,Thanks.

**Comment by mscdex** [comment]
Ah, ok, so that confirms it then. The server reply is never received for whatever reason.

If you have admin access on the server machine, it would be interesting to see if the OpenSSH server is sending back a reply or not in the `ssh2` 1.7.0 case. You could do that a few different ways.

One way might be to spin up a temporary copy of the OpenSSH server in debug mode with the verbosity turned up all the way and it should tell you what packets it is sending and receiving.

Another way would be to use Wireshark directly on the server or use tcpdump (with the appropriate flags) on the server to capture the traffic and then use Wireshark locally to read that capture.

If the OpenSSH server is either *not* receiving the client's KEX ECDH_INIT packet or *is* sending a KEX ECDH_REPLY packet, then that means there is something in between that is dropping the traffic in this specific case (e.g. security software, firewall, intrusion detection software, etc.).
