### ISSUE TITLE
How to reuse the same SSH tunnel for many different outbound connections?

### ISSUE THREAD

**Issue by neongreen** [mscdex/ssh2#1150]
My goal is to use node-postgres to execute queries against many different DB hosts using a single jump proxy.

I looked at https://github.com/mscdex/ssh2/issues/67 but it seems to use one SSH connection per one DB host. I'd like to use the same connection for many different DB hosts.

I could set up a socks proxy but I don't feel comfortable with plaintext authentication. Public-key authentication seems better.

Is this possible to achieve with ssh2?

**Comment by mscdex** [comment]
If your database driver can accept any plain duplex stream as the underlying connection, then all you need is to call `forwardOut()` and pass the stream from the callback to your database driver.

If your database driver does not have such support, then you need to set up some kind of local TCP server for making such connections that is a proxy between the database driver and the stream from `forwardOut()`. This is much like the example I gave in the issue you linked to.

In the case of `pg`, it looks like they've added support for custom streams at some point (although strangely it remains undocumented), so as far as I can tell from a brief look at their current code you should just be able to pass `stream: streamFromForwardOut` in your connection config object when you create a new `pg.Client()`.

**Comment by neongreen** [comment]
I have ended up using ssh2-promise and `.addTunnel` and it works, but I have very little understanding of SSH and tunneling so the hard part for me is understanding how well it would scale if I'm connecting to N hosts and correspondingly create N tunnels.

I'd love to be able to just say "please forward all traffic through [here], regardless of the destination". Then I could be sure it doesn't suffer from some kind of resource leak, etc. But I don't know if this is even achievable with SSH or with pg's `stream` interface.

**Comment by mscdex** [comment]
You can call `forwardOut()` as many times as the SSH server will allow you. The problem is you never know what that limit is going to be. I believe default OpenSSH server configurations have this limited to 10, although IIRC that includes all types of "channels" (e.g. as created with `forwardIn()`, `exec()`, `shell()`, and others) not just (client -> server) forwarded TCP connections.

So depending on your needs you might be able to get by with only a single connection, but you might need additional. It'd probably be best though to just write something that doesn't make such assumptions. That something would basically maintain some pool of SSH connections that you can call `forwardOut()` on. The logic would be something like:

0. <Startup, empty SSH connection pool>
1. User needs a database connection / needs to make a query
2. Add a new SSH connection to the SSH connection pool
3. Call `forwardOut()`
i. If it succeeds, pass the stream to `pg` and give that object to the user. If you intend to reuse the `pg.Client` instances you create, you will need to store them somewhere.
ii. If it doesn't succeed, assume you've hit a server limit. You may want to store the number of `forwardOut()` streams you currently have open when this happens so that you can simply use a conditional to check if a connection is free as an optimization instead of having to check if `forwardOut()` results in an error every time. Either way, you will need to go back to step 2.

It's up to you how you want to handle releasing of completely idle SSH connections, so that you don't keep them around forever, but that's the gist of it.

Lastly you might be able to simplify some of this if `pg` supports extending their `pg.Pool` class. That way you would just need to handle the underlying stream/connection creation (using the logic above) and `pg` would handle all of the creation and maintaining of `pg.Client` instances for you.

**Comment by neongreen** [comment]
Ok, thank you! I was definitely not expecting the default to be as low as 10 — this is useful to know.
