### ISSUE TITLE
Public key + password auth - Client fails

### ISSUE THREAD

**Issue by bgardner-noggin** [mscdex/ssh2#1187]
I have an SFTP server which is configured to require both a public key and a password

The current implementation of ssh2 does not handle this without providing an overriding authhandler eg

`const fs = require('fs');
const Client = require('ssh2-sftp-client');

let sentPublicKey = 0;
let sentPassword = 0;

const config = {
	host: '<host>',
	username: '<user>',
	privateKey: fs.readFileSync('<path to private key>'),
	passphrase:'<passphrase for private key>',
	debug: (msg) => {
		console.log('Debug ' + msg);
	},
	password: '<password for user>',
	authHandler: (curAuthsLeft, curPartial, doNextAuth) => {

		if (! sentPublicKey) {
			sentPublicKey = true;
			return 'publickey';
		}

		if (! sentPassword) {
			sentPassword = true;
			return 'password';
		}

		return false;

	}
};

const sftp = new Client('test');

sftp.connect(config).then(() => {
	console.log('Connected')
}).catch(err => {
	console.log('Error');
	console.log(err);
});`

**Comment by bgardner-noggin** [comment]
[issue-1187.patch.txt](https://github.com/mscdex/ssh2/files/8800921/issue-1187.patch.txt)
Patch that resolves the bug

**Comment by mscdex** [comment]
Using an `authHandler` is already the correct way of overriding the default order. Changing the defaults isn't really an option because it could break existing users.

I should also note that FWIW you can provide an array of properly formed objects instead of supplying a function, which would avoid the need to keep authentication state around. This array is then used in place of the default authentication method order and tries each method in the array in order.

**Comment by bgardner-noggin** [comment]
I guess, but it seems non intuitive that a common method, publickey + password, requires additional, non obvious, configuration.

The other potential patch is to have password in the list of auth methods twice, eg

```
if (privateKey !== undefined) {
  authsAllowed.push('publickey');
  if (this.config.password !== undefined) {
    authsAllowed.push('password');
  }
}
```

which would not change the order.

**Comment by mscdex** [comment]
At this point I'm not willing to risk that kind of breakage.

Additionally, you should be able to just pass strings instead of just objects: `authHandler: [ 'publickey', 'password' ],` if you prefer to have your credentials in the main config object passed to `connect()` instead of individual objects. I think the documentation is lacking this note.

**Comment by theophilusx** [comment]
bgardner-noggin ***@***.***> writes:

> I guess, but it seems non intuitive that a common method, publickey + password, requires additional, non obvious, configuration.
>

Is this really a common configuration? It certainly isn't one I've come
across very often (if at all!). My experience has definitely been that
you either have password OR public key, but not both. Systems would
tyhpically prefer/prioritise public key and might drop back to password
if public key fails.

**Comment by bgardner-noggin** [comment]
This is not fallback to password, this is publickey followed by password.

There is code to handle this already in the lib/client.js. See the partialSuccess/curPartial variables in this function below

```
        USERAUTH_FAILURE: (p, authMethods, partialSuccess) => {
          if (curAuth.type === 'agent') {
            const pos = curAuth.agentCtx.pos();
            debug && debug(`Client: Agent key #${pos + 1} failed`);
            return tryNextAgentKey();
          }

          debug && debug(`Client: ${curAuth.type} auth failed`);

          curPartial = partialSuccess;
          curAuthsLeft = authMethods;
          tryNextAuth();
        },
```
