### ISSUE TITLE
Error while attempting to import ssh2 via require() in React Class Component

### ISSUE THREAD

**Issue by akshaygh0sh** [mscdex/ssh2#1188]
I'm currently working on a web-based terminal that allows the user to issue commands on a device via SSH. I am getting the following (very weird) error when trying to use the ssh2 library.

For reference, I try to import the library within a member function called connect() in a React class component (which is exported), which causes the specific page of my app to not load. As of right now, the only code within this member function is as follows:

`connnect () {
        console.log("Testing before import")
        var Client = require('ssh2')
  }`

removing the `var Client = require('ssh2')` code results in the error disappearing and the page actually loading.

The two errors that I'm actually observing are:

> TypeError: Cannot read properties of undefined (reading 'DEFLATE')
    at Object.<anonymous> (zlib.js:7:5)
    at Object.<anonymous> (2.e61c8758.chunk.js:2:764751)
    at a (16:1:1346)
    at Object.<anonymous> (kex.js:48:5)
    at Object.<anonymous> (2.e61c8758.chunk.js:2:472513)
    at a (16:1:1346)
    at Object.<anonymous> (Protocol.js:56:5)
    at Object.<anonymous> (2.e61c8758.chunk.js:2:761250)
    at a (16:1:1346)
    at Object.<anonymous> (client.js:35:18)

> Uncaught TypeError: Cannot read properties of undefined (reading 'DEFLATE')
    at Object.<anonymous> (zlib.js:7:5)
    at Object.<anonymous> (2.e61c8758.chunk.js:2:764751)
    at a (16:1:1346)
    at Object.<anonymous> (kex.js:48:5)
    at Object.<anonymous> (2.e61c8758.chunk.js:2:472513)
    at a (16:1:1346)
    at Object.<anonymous> (Protocol.js:56:5)
    at Object.<anonymous> (2.e61c8758.chunk.js:2:761250)
    at a (16:1:1346)
    at Object.<anonymous> (client.js:35:18)

Any sort of insight as to what I'm doing wrong would be appreciated, thanks for your help!

**Comment by theophilusx** [comment]
The ssh2 library is a node library and does not work inside a browser
environment because it needs APIs which only exist in the node runtime
and not browser JS runtimes.

**Comment by mscdex** [comment]
I can only really help if you're using `ssh2` directly from node.js because that's where I test and what this module was originally designed for.

If you're trying to use `ssh2` from Electron, nw.js, or trying to use `ssh2` directly from the browser as-is (which won't work because of the node APIs that are required), you'll have to look to the appropriate forums for those projects.

**Comment by mscdex** [comment]
Typically the SSH connection happens on the backend and the frontend just provides the terminal display (e.g. xterm.js) for interactive sessions. Browsers don't have the ability to do direct TCP connections yet.

**Comment by akshaygh0sh** [comment]
Alright, I think I'll end up using socket.io to essentially connect the frontend to the backend. Thanks for all your help!

**Comment by theophilusx** [comment]
No, I suspect it would be very difficult to do because the browser JS
runtime simply lacks the low level API needed to perform the basic
crypotographic operations needed. 

I suspect the best you could really do is some form of proxy
architecture where the web browser only provides the UI elements and the
operations are performed on a server, where you have access to richer
environments than you find inside a browser. The downside of course is
that then you also need to add session isolation and manage possible
load issues etc. Of course a lot also depends on what exactly your
trying to do and why you feel you need ssh (in addition to standard
https/tls). 

There might be possibilities using technology like wasm, but I only have
a very cursory understanding of web assembly and don't know what the
limitations are. 

This is also assuming you are limited to just a browser environment.
There are of course alternatives, like electron, which has both the
browser process and a node process and built-in inter-process
communication which would allow development of a UI based on web
technology like react, but also support running node libraries needing
the broader node API.
