### ISSUE TITLE
not support openSSH6.2?

### ISSUE THREAD

**Issue by 805560947** [mscdex/ssh2#1208]
not support openSSH6.2 ?

**Comment by mscdex** [comment]
If I had to guess, maybe your problem is with the default ciphers? You can manage those by setting `algorithms` appropriately in the config object passed to `connect()`.

If that's not the problem, please describe what problem you're actually running into. There is no OpenSSH 6.2 compatibility issue.

**Comment by 805560947** [comment]
> If I had to guess, maybe your problem is with the default ciphers? You can manage those by setting `algorithms` appropriately in the config object passed to `connect()`.
> 
> If that's not the problem, please describe what problem you're actually running into. There is no OpenSSH 6.2-specific compatibility issue.

**Comment by 805560947** [comment]
> If I had to guess, maybe your problem is with the default ciphers? You can manage those by setting `algorithms` appropriately in the config object passed to `connect()`.
> 
> If that's not the problem, please describe what problem you're actually running into. There is no OpenSSH 6.2-specific compatibility issue.

![image](https://user-images.githubusercontent.com/31033695/187628782-c358eac8-fc1d-47e9-98bf-fe63044cfb25.png)

Maybe the cause of  the problem is  `algorithms`  ，so I have to update OpenSSH , I didn't  find other solutions.
