### ISSUE TITLE
Is it possible to directly use the stream in forwardOut for web page return?

### ISSUE THREAD

**Issue by alanhg** [mscdex/ssh2#1220]
now, I save multi-active connection. the server has [codeserver](https://github.com/coder/code-server) web, I want to access it through proxy, because it does not support external network access itself. Because there are different target machine services, here I store multiple connections.

I get each connection-stream. But I don't know how to use it in my WEB service now, because I want a sub-route to be adjusted to the WEB service route of the target machine, so as to proxy its content. Because the codeserver web has WS requests in addition to HTTP, so here I have two routing processes that require the final proxy to access the codeserver

I'm not sure if my solution is correct for this requirement.

The fundamental problem is that I want to proxy access to the codeserver-web service of the target machine by my sub-route web. 

I understand that this problem is not part of the SSH2 module, but I don't know how to use the stream here, or do I need net.createServer?

## I want to be
just visit http://localhost:8080/ws/<serverID> like visit  http://<serverID>

## code

```js

class CodeServerProxifier extends EventEmitter {
  constructor() {
    super();
    /**
     * key为ip,value为CodeServerProxy，方便动态代理到目标机器
     * @see CodeServerProxy
     */
    this.codeServerPool = new Map();
  }

  connect(connectOpts) {
    if (this.codeServerPool.get(connectOpts.host)) {
      this.emit('ready');
    } else {
      let codeServerProxy = new CodeServerProxy();
      codeServerProxy.forwardOut(connectOpts)
        .on('ready', () => {
          this.codeServerPool.set(connectOpts.host, codeServerProxy);
          this.emit('ready');
        });
    }
    return this;
  }
}

class CodeServerProxy extends SshClient {


  constructor() {
    super();
    this.stream = null;
  }

  /**
   * 正向代理
   */
  forwardOut(connectOpts) {
    const client = new SshClient();
    client.connect(connectOpts).on('ready', () => {
      client.conn.forwardOut('0.0.0.0', proxyWebPort, '127.0.0.1', remoteCodeServerPort, (err, stream) => {
        if (err) {
          throw err;
        }
        this.stream = stream;
        this.emit('ready');
        // sock.pipe(stream);
        // stream.pipe(sock);
      });
    });
    return this;
  }

  close() {
    this.stream && this.stream.close();
  }

}
```

![image](https://user-images.githubusercontent.com/9245110/192155764-7e3aaa56-798a-4635-9d8c-2eb095695b10.png)

**Comment by mscdex** [comment]
`ssh2` does not listen on any ports locally when you call `forwardOut()`. The local IP and port you pass it are purely informational and it's up to the ssh server to use that information how it wants (thus you can usually set them to the same fixed values if you wish). The more important information is the remote/destination IP and port because the ssh server definitely would use that in order to connect to your destination.

The stream given by `forwardOut()` is a raw byte stream representing a connection to the destination IP and port. Think of it as the kind of stream you'd get when using `net.connect()`. That means if the destination IP and port is an HTTP server, you can expect to speak HTTP over that stream. If it's an HTTPS server, you can expect to speak HTTPS over that stream.

What you do with that stream is up to you. If you are trying to proxy local web requests to some upstream web server, there are at least two solutions you could go with:

1. Set up a traditional HTTP/HTTPS proxy that listens on localhost that proxies connections over SSH
2. Find a way to do it all in process using a node `http.Agent`/`https.Agent` that utilizes streams from `forwardOut()` instead of regular TCP sockets. `ssh2` actually [already exposes such Agents](https://github.com/mscdex/ssh2#httpagent) that you can pass to node's `http.request()`/`https.request()`. These agents will do the `forwardOut()` for you and node will manage the open streams for you (you can also pass the usual [`http.Agent()`/`https.Agent()` settings](https://nodejs.org/docs/latest/api/http.html#new-agentoptions) to limit the number of (SSH) connections being made for example). If you're proxying a websocket connection, you'd need whatever websocket client library to also support such `Agent` instances.

**Comment by alanhg** [comment]
> `ssh2` does not listen on any ports locally when you call `forwardOut()`. The local IP and port you pass it are purely informational and it's up to the ssh server to use that information how it wants (thus you can usually set them to the same fixed values if you wish). The more important information is the remote/destination IP and port because the ssh server definitely would use that in order to connect to your destination.
> 
> The stream given by `forwardOut()` is a raw byte stream representing a connection to the destination IP and port. Think of it as the kind of stream you'd get when using `net.connect()`. That means if the destination IP and port is an HTTP server, you can expect to speak HTTP over that stream. If it's an HTTPS server, you can expect to speak HTTPS over that stream.
> 
> What you do with that stream is up to you. If you are trying to proxy local web requests to some upstream web server, there are at least two solutions you could go with:
> 
> 1. Set up a traditional HTTP/HTTPS proxy that listens on localhost that proxies connections over SSH
> 2. Find a way to do it all in process using a node `http.Agent`/`https.Agent` that utilizes streams from `forwardOut()` instead of regular TCP sockets. `ssh2` actually [already exposes such Agents](https://github.com/mscdex/ssh2#httpagent) that you can pass to node's `http.request()`/`https.request()`. These agents will do the `forwardOut()` for you and node will manage the open streams for you (you can also pass the usual [`http.Agent()`/`https.Agent()` settings](https://nodejs.org/docs/latest/api/http.html#new-agentoptions) to limit the number of (SSH) connections being made for example). If you're proxying a websocket connection, you'd need whatever websocket client library to also support such `Agent` instances.


I want to confirm, for example, for the proxy WebSocket, can the httpagent exposed by ssh2 be used as a proxy for websocket?


![image](https://user-images.githubusercontent.com/9245110/194715866-c175d7a7-a43a-4deb-9d7c-5f10a9cd4403.png)

**Comment by mscdex** [comment]
You'll have to check with the websocket module to see if it has support for it in one way or another.

**Comment by alanhg** [comment]
> You'll have to check with the websocket module to see if it has support for it in one way or another. In theory though, since websockets are just upgraded http connections, it should work.

Thank you. I solved.
