### ISSUE TITLE
How to close SftpChannel?

### ISSUE THREAD

**Issue by alanhg** [mscdex/ssh2#1305]
For example, here I use a connection to obtain an SFTP channel. When I'm in the middle of an upload and I want to cancel it without closing the SSH connection, my understanding is that I can simply close this channel, right?

![image](https://github.com/mscdex/ssh2/assets/9245110/3cdba95b-d86c-4584-9de0-5e88667f38ac)

 I see that the close method of the channel has two parameters during debugging, but I'm not sure what should be passed specifically.

![image](https://github.com/mscdex/ssh2/assets/9245110/7428f24f-6e1e-46a7-9066-37220076cc8a)

**Comment by mscdex** [comment]
`sftp.end()` should close the channel.

**Comment by alanhg** [comment]
Thank you, I understand. So, sftp.end does not close the SSH connection; it only closes the specific channel.

 I would like to ask, based on my previous description, if closing the channel and reestablishing it is a recommended approach for implementing upload cancellation. I'm not sure if FileZilla or other applications use this approach.

**Comment by mscdex** [comment]
Each call to `ssh.sftp()` is a separate channel. If you are performing multiple transfers on the same SFTP channel, then simply only stop the transfer you want. If you're using `sftp.fast*()`, you either need to create your own solution and/or keep an eye on [this feature request](https://github.com/mscdex/ssh2/issues/1299). Otherwise if you're using a file stream, you simply just need to destroy it.
