### ISSUE TITLE
Timeout waiting for handshake

### ISSUE THREAD

**Issue by bonnellyk** [mscdex/ssh2#1325]
I'm working with my partner on identical laptops.
We have a node API that connects to our DigitalOcean server through ssh2 and runs a few commands.

Out of nowhere, my partner's laptop started being unable to connect to the server. He's getting "**Timeout waiting for handshake**".
But I was not able to reproduce the error on my end, it's only on his laptop that it happens.

So far we tried the following:
- readyTimeout: 99999
- Excluding diffie-hellman-group1-sha1 from the algo
- Enabling UseDNS on the server's sshd_config
- Creating a new server on DigitalOcean
- Re-creating the ssh-key
- Adding a on('keyboard-interactive') with tryKeyboard:true, didn't get in
- Connecting with ssh user@host directly works fine
- Connecting with ssh chrome plugin works fine as well
- auth.log on the server shows that the user was logged in.

We've also seen the error "All authentication methods failed" in the past.

Any idea what could cause this? Or tips to troubleshoot?
We have the exact same setup, except he ran the commands more often than me.

**Comment by mscdex** [comment]
As far as slow handshaking goes, that's going to happen for any key exchange algorithm that is not curve25519-sha256 because OpenSSL does some computationally intensive calculations to ensure the diffie hellman exchange parameters are "safe".

To be more certain what is the cause, you can set `debug: console.log` in the connection config object to get debug output. From there it should be evident whether it's not making a connection at all, if it's stalling after exchanging algorithms and it's the aforementioned OpenSSL slowdown causing the issue, or if it's something else entirely.

**Comment by mscdex** [comment]
Also FWIW, the (technical) reason why you don't see the diffie-hellman slowdown in OpenSSH is because it doesn't utilize `DH_check()` from OpenSSL, which is where the slowdown occurs. Node.js *does* use that function to validate the key exchange parameters.

It wasn't always that way, it wasn't until [this commit in OpenSSL](https://github.com/openssl/openssl/commit/2500c093aa1e9c90c11c415053c0a27a00661d0d) that the slowdown started to occur, which increased the number of checks being performed.

**Comment by mscdex** [comment]
Additionally can you include what node version you're using in both cases?
