### ISSUE TITLE
[HELP]  how can I set `RequestTTY` option

### ISSUE THREAD

**Issue by RightFS** [mscdex/ssh2#1327]
As the title says, I have a server wihch have some stupid output in bashrc, so I need set an option to ssh client to prevent the output from server to make `scp` work correctly;

[SCP fails without error](https://unix.stackexchange.com/questions/18231/scp-fails-without-error)

<img width="720" alt="image" src="https://github.com/mscdex/ssh2/assets/12915306/864207f5-3953-46ac-93c7-01c1d9f4c32f">

**Comment by mscdex** [comment]
`exec()` doesn't request a pty by default, but `shell()` does. Both methods allow you to configure whether a pty is requested and the parameters (e.g. dimensions, terminal type, etc.) associated with it.

My suggestion is to just use `exec()` to call scp on the remote side. Do note however that `ssh2` does not have scp (protocol) support built-in. Also recognize that some systems with the OpenSSH client installed have the scp command actually use sftp under the hood instead of the scp for the underlying protocol.
