### ISSUE TITLE
Output cut off in the middle during a stream

### ISSUE THREAD

**Issue by AlexandreSama** [mscdex/ssh2#1348]
Hello ! 

Currently, I retrieve the stream to display it in my terminal, but I noticed that a piece is missing each time as shown in the image:
![Capture d'écran 2023-11-21 124549](https://github.com/mscdex/ssh2/assets/56075082/cf560674-4a54-4cbb-a7bc-1fcde102074d)

Is there a solution to this? Here is my code:
```js
const conn = new SSHServer();
conn.on('ready', () => {
    console.log('SSH Client :: ready');
    conn.shell((err, stream) => {
        if (err) throw err;
        sshStream = stream;
		stream.setDefaultEncoding('utf-8')
        stream.on('close', () => {
            console.log('SSH Stream :: close');
            conn.end();
        }).on('data', (data) => {
			clients.forEach(client => {
                if (client.readyState === 1) {
					// const doubleCleanData = data.replace('', '')
					console.log(data)
                }
            });
        });
		sshStream.write('screen -x ServerTest\n');
    });
})
```

**Comment by mscdex** [comment]
I see two issues here:

1. `stream.setDefaultEncoding('utf-8')` is likely not doing what you think it's doing. It only sets the default encoding when you pass a string to `stream.write()`. If you want `'data'` event handlers to receive well-formed utf-8 strings instead, you need to use `stream.setEncoding('utf-8')`.

2. You're executing screen, which utilizes terminal escape sequences to do what it needs to do. That means you can't necessarily just `console.log(data)` and have the resulting output make sense. At the very least you should `process.stdout.write(data)`. This is also assuming that you're *not* using `stream.setEncoding()` or otherwise converting `data` to string as that will wreck the terminal escape sequences written by screen.
