### ISSUE TITLE
how to choose between shell or exec function ?

### ISSUE THREAD

**Issue by dineshmickey** [mscdex/ssh2#1351]
I'm developing an framework for Network Configuration Manager which logins into many routers and switches / firewalls . 

Some of the devices works seamless with .exec function but some doesn't , but it works with .shell function  

After the establishment of the connection , how do i determine whether to run shell or exec commands ?

Could you please help

**Comment by mscdex** [comment]
I can't help you there. If you have SSH servers that only accept one or the other you just have to either know which one to use or try one and if you determine by some method that it's not working, fall back to the other method.

**Comment by dineshmickey** [comment]
Sure ,
I have used shell to execute the command , but the stream close event is not triggered  after executing the commands , How could i determine the data is completed or not , in that case 

any idea on the behavior
 
I have seen some packages like ssh2shell , they have implemented idle timeout to handle this scenario , is there any other way , 
Correct me if am wrong or misunderstood

**Comment by mscdex** [comment]
I can't tell you why the server is not closing the stream, assuming you're telling it to do so via a command or some other method.

Either way, I think you should probably add a timeout of some kind for embedded devices like this as they are especially finicky not only due to their buggy/non-compliant SSH implementations but also because they are often presenting custom interfaces (vs. presenting a traditional shell) which means you are at the mercy of that specific vendor's code.

**Comment by rfsilvagyn** [comment]
I need to access the equipment and disconnect users, how can I solve this?
