### ISSUE TITLE
Can't connect "ignoring handled error"

### ISSUE THREAD

**Issue by palbrecht1** [mscdex/ssh2#1357]
I've been struggling to make SSH2 to work on a fresh node:20-bullseye image. It does work on a latest mac os developer machine, but fails to work when running in the cloud.

The logs below only show **"connect errorListener - ignoring handled error** and subsequently **Global error event: Ignoring expected and handled event**

Sadly none of these messages help debug the situation.

I am using the ssh2-sftp-client wrapper, but this seems to be an SSH2 specific issue.

![CleanShot 2024-01-07 at 18 32 57@2x](https://github.com/mscdex/ssh2/assets/53092932/e6590893-3ded-4737-ba4b-c15e8cb9b7e0)

**Comment by mscdex** [comment]
I can't really help you with third party packages as I am not familiar with them and those error messages are not coming from `ssh2`. Please try with `ssh2` directly and post the minimal code example that you tried.

However if I had to guess at the underlying issue, it's the lines *above* that that are key, namely the handshake timeout. Try increasing that in your connection configuration object.

**Comment by theophilusx** [comment]
I am maintainer of the ssh2-sftp-client module.

I think @mscdex is correct. Your focusing on the wrong log entries. The
two lines above what you have indicated are what are relevant. The two
lines you are marking simply tell you that the GLOBAL error handler is
ignoring the error because it was handled by the connection error
handler. Your issue is the handshake timeout error. 

Background Details

This might seem confusing, but it is something you have to deal with
when you are wrapping an event based API in a Promise API wrapper. In
the ssh2-sftp-client module each method (action) is wrapped in a promise
which either gets fulfilled or rejected. Each promise adds listeners for
various events, such as error events. These listeners are tied to the
encapsulating promise via the promises resolve/reject
functions. However, with a TCP connection, errors can occur in-between
method calls, when no promises are active. In these situations, the
global event handlers are used to handle events so that the code doesn't
just exit with an unhandled exception error. This does mean, when a
method Promise is active, there are two event listeners for an event,
such as an error event. The 'local' promise event listener and the
'global' event listener. Problem is, we don't want both event listeners
handling the same event. Therefore, code is added to track event
handling and if a global event listener sees and event which has already
been handled, it doesn nothing except log it has seen it. These are the
messages you have highlighted.

**Comment by palbrecht1** [comment]
@theophilusx Thanks for your message - how do you suggest we debug the timed out while waiting for handshake given there's no additional error log?

**Comment by palbrecht1** [comment]
Below is an SSH2 code snippet:

```
const { Client } = require('ssh2');

const conn = new Client();
conn.on('ready', () => {
  console.log('Client :: ready');
  conn.sftp((err, sftp) => {
    if (err) throw err;
    sftp.readdir('', (err, list) => {
      if (err) throw err;
      console.dir(list);
      conn.end();
    });
  });
}).connect({
  host: '***',
  port: 22,
  username: '***',
  privateKey: '***',
  timeout: 60*1000
});
```

It works when running on mac os from the console, but when running in our cloud environment I get this error

```
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/app/node_modules/ssh2/lib/client.js:1116:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Emitted 'error' event on Client instance at:
    at Timeout._onTimeout (/app/node_modules/ssh2/lib/client.js:1118:16)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  level: 'client-timeout'
}
```

**Comment by mscdex** [comment]
You can set `debug: console.log` to see if it's not connecting at all or if the handshake is taking too long. If it's the latter, you may be able to get by by increasing the default `readyTimeout`. The best you can do to minimize the handshake time is to use `curve25519-sha256`/`curve25519-sha256@openssh.com` for the key exchange algorithm as that isn't subject to the intensive checks that OpenSSL does for the diffie-hellman algorithms.

**Comment by theophilusx** [comment]
If you set a debug function for the debug property in the connect
options object, you will get a lot more debugging information. The debug
function could be a simple as console.log.

**Comment by palbrecht1** [comment]
I set the readyTimeout to 1min and added a debug function, below is what I'm getting.

```javascript
.connect({
  host: '***',
  port: 22,
  username: '***',
  privateKey: '***',
  debug: (e) => {console.log('DEBUG - ', e)},
  readyTimeout: 60*1000,
  timeout: 60*1000
});
```
![CleanShot 2024-01-15 at 09 42 31@2x](https://github.com/mscdex/ssh2/assets/53092932/5eb0333a-40a5-4f99-a0c0-6585f6f7eaa8)

**Comment by theophilusx** [comment]
Based on that debug output, my guess would be that your remote server is
simply not responding. Either the remote server is not getting the
connections or the responses form the server are not getting through.
From the log messages (or lack of them), it looks like your remote sftp
server simply isn't responding and eventually the client just times out.

For a comparison, run the same code (with debug function) and look at
what you get on a working system. You will see all the interaction
between your client and the remote sftp server as it exchanges keys and
negotiates the ciphers for the communication with the remote
server. Your not seeing any of that. 

I would do two things

1. Make sure you can connect to your sftp server using openSSH sftp from
the same server as your client is running

2. Check firewall settings. The only time I've seen this sort of
behaviour, it was a firewall configured to drop (not reject)
connections. I'd verify this isn't the issue.

The fact the code works outside your cloud environment would indicate
the problem is with your cloud environment and nothing that can be
addressed at the ssh2 or the ssh2-sftp-client level.

**Comment by palbrecht1** [comment]
After further investigation it seems indeed the issue is connected to the cloud platform's limitations, closing this issue.
