### ISSUE TITLE
Issue Connecting to MongoDB via SSH Tunnel in Node.js

### ISSUE THREAD

**Issue by bmasias1** [mscdex/ssh2#1372]
I'm attempting to connect my Node.js application to a remote MongoDB database through an SSH tunnel using the `ssh2` module and `mongoose`. While I can establish the SSH connection and port forwarding without issues, I run into difficulties when trying to use this connection for MongoDB access.

The attached code sets up the SSH tunnel and then attempts to connect to MongoDB using Mongoose. If I manually establish the SSH tunnel from the terminal (using `ssh -L 27017:localhost:27017 user@host -p port -N`) and then run my application, everything works as expected. However, when I try to do everything within my Node.js application, it seems like the tunnel is established, but the MongoDB connection either fails or doesn't occur as expected.

I've made sure the credentials and configurations are correct and also implemented error handling to debug the issue. Nonetheless, I can't pinpoint the exact cause of the failure in connecting to MongoDB through the programmatically established SSH tunnel.

Code Sample:
```
const { Client } = require('ssh2');
const mongoose = require('mongoose');
const MyModel = require('./models/MyModel');

async function testSSHMongoConnection() {
  const conn = new Client();

  conn.on('ready', async () => {
    console.log('SSH Client :: ready');

    // Forward the MongoDB port
    conn.forwardOut('127.0.0.1', 50000, '127.0.0.1', 27017, async (err, stream) => {
      if (err) {
        console.error('SSH Forwarding Error:', err);
        return conn.end();
      }
      console.log('SSH Forwarding setup successfully');

      const dbURI = "mongodb://127.0.0.1:50000/yourDatabase";

      try {
        await mongoose.createConnection(dbURI, {
          useNewUrlParser: true,
          useUnifiedTopology: true,
        });
        console.log("Connected to database through SSH tunnel");

        const model = mongoose.model('MyModel', MyModel.schema);

        // sample query
        try {
          const count = await model.countDocuments({});
          console.log('Document Count:', count);
        } catch (err) {
          console.error('Error counting documents:', err);
        }

        mongoose.disconnect(() => {
          console.log('Database connection closed');
          conn.end();
        });
      } catch (err) {
        console.error('Database connection error:', err);
        conn.end();
      }
    });
  });

  conn.on('error', (err) => {
    console.error('SSH Connection Error:', err);
  });

  conn.connect({
    host: 'SSHHost',
    port: SSHPort,
    username: 'SSHUsername',
    password: 'SSHPassword',
  });
}

testSSHMongoConnection();
```

Has anyone faced a similar issue or has suggestions on what might be wrong or how to resolve this problem?

Thank you in advance for any help or insight.

**Comment by mscdex** [comment]
For tunneling connections you need one of the following:

1. A node module that also allows supplying a plain stream as its underlying "socket". This is the recommended route if possible as it skips the need for intermediary TCP servers and sockets. Not all database client modules support that unfortunately, although adding support for that should be pretty trivial.

2. A `net.Server` that listens for local inbound connections and then calls `ssh.forwardOut()` for each new connection, piping between the connection and the `forwardOut()` stream. This is what happens when you do something like `ssh -L8000:localhost:80 ...` with the OpenSSH client.

In either case it's important to remember that SSH servers almost always have limits on the number of simultaneous forwarded connections they will allow, so you may need to utilize multiple SSH connections.
