### ISSUE TITLE
There are newlines in the end of output stream when using the exec method

### ISSUE THREAD

**Issue by ivanduplenskikh** [mscdex/ssh2#1425]
**Description:** When using the **exec** method from the **ssh2** module, newlines (CR/CRLF) appear at the end of output stream.
This occurs after executing a command on a remote server through the **exec** method, such as the **echo** command.
Here is a straightforward example for reproduction:

```js
const { Client } = require('ssh2');

const sshClient = new Client();

sshClient
    .on('ready', () => {
        sshClient.exec('echo "Debug output"', (err, stream) => {
            if (err) throw err;

            const isRemoteWindows = sshClient._remoteVer.indexOf('OpenSSH_for_Windows') !== -1;
            const newline = isRemoteWindows ? '\r\n' : '\n';

            stream
                .on('close', () => {
                    console.log('Client disconnected');
                    sshClient.end();
                })
                .on('data', (data) => {
                    console.log(data.toString('utf-8'));
                    console.log(isRemoteWindows ? 'Windows' : 'non-Windows');
                    console.log(data.indexOf(newline) === data.length - newline.length ? "The newline is found" : "No newline");
                });
        });
    })
    .connect({
        host: process.env['SSH_HOST'],
        port: 22,
        username: process.env['SSH_USER'],
        password: process.env['SSH_PASSWORD'],
    });
```

Output for **Windows** remote server:
```pwsh
Debug output

Windows
The newline is found
Client disconnected
```
Output for **Ubuntu** remote server:
```bash
Debug output

non-Windows
The newline is found
Client disconnected
```

**Additional information:**
- ssh2 module: **^v1.15.0**
- Node.js Version: **v16.20.2**, **v20.17.0**
- Client OS: **Windows 11**
- Server OS: **Windows 10**, **Ubuntu 22.04**

Is this the intended behavior, and if so, can it be adjusted by adding specific properties to the Client or connection settings?

**Comment by mscdex** [comment]
That's the default behavior of `echo`. You'd need to use `echo -n` to suppress the trailing newline. Additionally, `ssh.exec()`/`ssh.shell()`/etc. does not mangle or otherwise interfere with the data coming from the server.

**Comment by avishnyakov** [comment]
Right, interesting. A few notes here
* https://github.com/microsoft/azure-pipelines-tasks/issues/20472#issuecomment-2392498832

I don't understand a few things here
* Azure DevOps: same bash script should produce same outputs under (1) bash and (2) SSH tasks, right?
* SSH tasks seems to add extra new line, unclear why
* `echo -n` is not a solution, because same bash script should produce same outputs under (1) bash and (2) SSH tasks, right?
* then, we run other binaries under SSH tasks: for example, maven / gradle builds, Apache ANT builds, other binaries - and we get extra new line for output (so where do we add `-n` parameter for such binaries?)

Understand assumption that SSH2 module does not change output - this is fine. What I don't understand is what causes same bash script to produce same outputs under Azure DevOps (1) bash and (2) SSH tasks. Recon reasonable expectation is that same bash script produces same output under both tasks? If not, we should understand why it's different and how to control it.

**Comment by mscdex** [comment]
@avishnyakov You should probably start with whatever is using `ssh2`. In this case you'll probably want to focus on [this file](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/SshV0/ssh2helpers.ts).

A brief look reveals some questionable command output handling:

* There's an assumption being made that `data` events are always emitting complete characters (which may not be the case if you are dealing with non-ASCII characters). This is not a correct assumption. A `data` event is emitted for a chunk, which can be any number of bytes and may or may not have a character split across chunk boundaries for example.
* `console.log()` is being used to output each chunk. This is a problem for two reasons: 1) you may not get the entire command output in a single chunk and 2) `console.log()` adds a newline of its own to whatever value you pass it, which could be the cause of your problem.
* The stdout stream `data` event handler has a `dataBuffer` string that's being passed to a function where it then gets concatenated with incoming chunk. This is useless because strings are passed by value, so the caller's `dataBuffer` will never get updated.

This is just scratching the surface. There may be additional issues. Good luck.

**Comment by avishnyakov** [comment]
Right, two points might explain another mystery with Azure DevOps SSH task which we see in our CI/CD pipelines - "random" line breaks for what suppose to be a single line. 

Not only we have line break for each `echo` command, other commands which seem to be sub-shell execution, and binary tools like maven, gradle, apache ant, git - but we also have below random line breaks

The two point above seem to explain this behavior. I don't have enough expertise in terminals, tty and ssh and how it all works. With best reading, looks like output indeed can be buffered or buffered, coming in chunks back into terminal or something. With SSH session, it can also be preudo tty or something. So at the end, looks like Azure DevOps SSH@0 task needs to handle coming data correctly? 

Here is what we see in bash script + binaries executed under DevOps SSH@0 task
* green are random breaks - they are indeed random, without any pattern
* happen on bash, git, maven, gradle, Apache ant output
* hapens for both colored and plain output
* no specific pattern - can be a few chars, and break, can be two or three lines breaks


![image](https://github.com/user-attachments/assets/f47bd9b5-1571-4c96-98fe-7b7c3187b16b)

**Comment by avishnyakov** [comment]
> console.log() is being used to output each chunk. This is a problem for two reasons: 1) you may not get the entire command output in a single chunk and 2) console.log() adds a newline of its own to whatever value you pass it, which could be the cause of your problem.

Sounds like we just need to dump SSH2 output as it comes, without `console.log()` - because SSH2 output would have correct line breaks. The question is how to handle chunks, or by the sound of things, we don't need to and also need to just dump everything right into console 😭
