### ISSUE TITLE
How do I handle symbols in messages from the server

### ISSUE THREAD

**Issue by Canees** [mscdex/ssh2#1427]
This is just another topic and may not be relevant to this library
Want to correctly display the message returned by the server in the web page, I would like to ask everyone to have any good suggestions?

![image](https://github.com/user-attachments/assets/308b0c4e-7ab3-4acb-9a57-3d71360b587b)

**Comment by mscdex** [comment]
Those are terminal escape sequences. As long as your terminal type is correct, you just need to write the raw data (don't convert to strings) directly to your terminal instead of using `console.log()`/`console.dir()`/`util.inspect()`/etc. `pipe()`ing stdout to your `process.stdout` is usually sufficient.
