### ISSUE TITLE
Can't get "mode" option to work

### ISSUE THREAD

**Issue by callumlocke** [mscdex/ssh2#150]
I'm trying to create a remote directory like this:

`sftp.mkdir(currentDir, {mode: '0775'}, function (err) {`

But the directory always gets created with permissions `755`. 

I've tried setting it with `'0775'`, `'775'`, and `parseInt('0775', 8)`, but it never seems to take effect.

Am I doing it wrong?

Also, when I upload a file with `fastPut`, there's no documented way to set the permissions for that file. I tried adding `{mode: '0775'}` but it always gets created with `644`. I don't know if this is a separate issue or not.

**Comment by mscdex** [comment]
So the problem here is the umask that the OpenSSH SFTP server is using. For example, the default umask on Ubuntu (for me) is 0022. So trying to create a directory with 0775 will result in 0755 as you noted, because the umask overrides our mode.

An easy way to change this is to pass in the desired umask to the sftp server in the `/etc/ssh/sshd_config`. For example: `Subsystem sftp /usr/libexec/openssh/sftp-server -u 0002`. If your version of OpenSSH does not support `-u` you can use `Subsystem sftp /bin/sh -c 'umask 0002; /usr/libexec/openssh/sftp-server'` instead. Replace `/usr/libexec/openssh/sftp-server` with `internal-sftp` if you are using the internal sftp server.
