### ISSUE TITLE
Please, add support for expanding "~/" to home dir in SFTP remotePath

### ISSUE THREAD

**Issue by afanasy** [mscdex/ssh2#212]
so it's possible to sftp.fastPut('file.txt', '~/'), using the same syntax as command line scp

**Comment by mscdex** [comment]
sftp doesn't support that kind of thing. scp supports it because scp is more or less `ssh.exec('cat > ' + remotePath, ...);`. Which you could do exactly that if that works for you. Otherwise you should be able to upload relative to the home directory with sftp by simply stripping off the leading `~/` since sftp sessions typically already start relative to the user's home directory.

**Comment by afanasy** [comment]
Ok, thanks!
