### ISSUE TITLE
Socket unref

### ISSUE THREAD

**Issue by xxorax** [mscdex/ssh2#217]
I try to call [unref](http://nodejs.org/api/net.html#net_socket_unref) on the socket, to allow the process exit without waiting the end of the socket.
So I try to do in the "ready" event (where the socket is initialised) :
```
conn.once('ready', function () {
  conn._sock.unref();
```
But it seems not work... (I'm on node v0.10.35)

Is there other socket I should care ?
Or Is it possible you implement an option for this ?

Thanks !

**Comment by mscdex** [comment]
The reason is that by default in ssh2 v0.3.x, there is a ping interval that is set up. You can disable this by setting `pingInterval: false` in your config options. Or if you want to dig into the internals to disable the timer manually, you can do `clearInterval(conn._pinger);`.

In ssh2 v0.4.x, the keepalive timer is not on by default so `unref()`'ing the socket is enough.
