### ISSUE TITLE
Can SSH2 work with SFTP SOCKS?

### ISSUE THREAD

**Issue by dberry-98** [mscdex/ssh2#236]
Love this project and it works great but was wondering if it works with SFTP and SOCKS5?

**Comment by mscdex** [comment]
There are examples of both in the readme.

**Comment by dberry-98** [comment]
Thanks for the quick response. The example I see below is for running a SOCKS server and uses curl as the client. Is there anything for running an SFTP/SSH client with SOCKS support instead of using curl?

Dynamic (1:1) port forwarding using a SOCKSv5 proxy (using socksv5):

**Comment by mscdex** [comment]
Yes, it would work similarly for a client. You can use the same `socksv5` module for connecting to the proxy. Once you're connected, you just set the stream from `socksv5` as the `sock` property in the settings object passed to `ssh2.connect()` and `ssh2` will use that stream instead of creating a new TCP socket.

**Comment by dberry-98** [comment]
Excellent, I'd suggest this sample go in the readme on the next rev. Thanks for your great responsiveness and support, I was getting ready to use python for this ;)

**Comment by serjN** [comment]
I think this code snippet should be in readme.md examples too.
