### ISSUE TITLE
Authenticating with password alone leads to botnet hijacking

### ISSUE THREAD

**Issue by wski** [mscdex/ssh2#245]
Using this module to ssh into a server has lead to multiple servers being hijacked for use as a DDoS botnet. At first I was concerned that it might be due to the application storing passwords in plain text (an obvious problem I plan to address) but I used the module without storing anything and without passing the password over any network other than through this module and within a few hours the server was compromised. 

Due to risking my Digital Ocean account status as well as my personal servers I have not tested using other authentication methods.

Notes:
System: OSX 10.10 running nwjs application locally 
Server: Digital Ocean test droplet running nodejs 
Authentication Method: username/password

Application in question: https://github.com/wski/gispatch

WARNING: DO NOT ATTEMPT TO LOGIN USING THIS APPLICATION ON A SERVER YOU CARE ABOUT-- ONLY USE A DISPOSABLE SERVER. (I would suggest destroying the OS on that server the moment you notice the attack taking place. I had noticed several processes running with random names.)

**Comment by wski** [comment]
Just as a side note this could be an issue with my local system or an issue in which I handle the information within my application but did not want to leave the possibility that this module or its methods could be being targeted unaddressed.

**Comment by unknownbrackets** [comment]
You should check the logs on a compromised server instance's disk to see how and when logins happened.  This might help you understand if it's your application and where the disclosure may have come from.  It would help you to understand if they logged in via ssh (e.g. obtaining a password), or piggy-backed on your application itself, or got in through other software your application added to the target server.

That being said, common best practice is to not use passwords at all, and instead use private keys (with a passphrase.)  You can essentially think of a private key as a very long password (except it's much better than that.)  The passphrase is then a password to even get to that very long password, again very basically.

I don't personally recommend having password-based ssh authentication enabled at all on cloud servers, like DigitalOcean.

-[Unknown]

**Comment by wski** [comment]
Noted, I have destroyed the droplet promptly to avoid having my account suspended or worse considering the amount of bandwidth usage coming from the server and the obvious malicious intent. I should however have backups from another machine. I did happen to capture the IP and the script installed but have not looked deeply into how it got there yet. 

Thanks for the advice !

**Comment by mscdex** [comment]
Closing this as this is not an issue unique to this module. As @unknownbrackets said, password-based authentication for SSH should always be avoided, especially when you're making SSH connections over the internet. Similarly even if you're using a private key for authentication, storing the passphrase for the encrypted key in plaintext in a node script is just as bad. IMHO the best authentication mechanism (currently) is using a private key via an SSH key agent such as `ssh-agent` on *nix/cygwin or [Pageant](http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html) (for non-cygwin users on Windows).

It's also entirely possible that your server or the machine you were connecting from was broken into via other means first. It's hard to say.

However if you have discovered an *implementation-specific* security issue with this module, please contact me privately so that it can be addressed in a proper manner.
