### ISSUE TITLE
ssh2 as a better repl

### ISSUE THREAD

**Issue by IngwiePhoenix** [mscdex/ssh2#254]
Hey!

First on - great work! When I installed the module, I was expecting native code to be compiled...but nope, not happening. Implenting ssh2 in raw JS looked like a hard task to me. so congrats on that one.

Now to my questions: 
I have an app that collects and monitors status. But further, I also wanted to implement some features that would work with clients connecting via a terminal. For instance, I have a chat application running within that is rendered to the browser...but a friend of mine is blind and would very much appreciate it if he could connect to it using his terminal. And thinking about it, it would work much better on slower connections too.

In order to do that, I would have needed to implement REPL. But... REPL and security? Let's face it; there is none. But ssh2 offers way better mechanics for that. In fact, from what I know, all SSH2 traffic is encrypted by default, which is why it basically kicked the old telnet stuff into the dumpster :). So this is something I am really looking forward to.

But I need some clarifications about this module that just didn't go into my head just yet:

- This module allows a client to have an interactive session. Which functions/events are responsible to parse the commandline?
- Will this block current execution? I am not sure if I should delegate a worker process to handle ssh2 or not...
- What exactly could I use a pseudo tty for? I know that my Terminal's terminfo is `xterm-256`...but if a Windows client connected, and I sent special characters, wouldn't the ANSI escapes be thrown at them in a raw manner? Will a pty prevent that? I am just not sure on these - sorry! :)
- In the README, you wrote:
```
// if no signature present, that means the client is just checking
// the validity of the given public key
```
What exactly is ment by that? I never saw my ssh client just sending a flat request.
- When running an interactive session, how do I define the prompt? How is that even printed? I know that in the case of traditional Bash, it executes a command and writes its prompt to STDOUT. Do I do the same - and how do I do that on successful authentification?

Sorry for the very long post, but I just want to be very sure before I get myself stuck in a wall! :)

Kind regards,
Ingwie

**Comment by mscdex** [comment]
I'm a bit confused about your use case. Are you wanting to implement an ssh server? Are you using "REPL" to mean "command line interface" or are you actually looking for a *real* REPL over ssh?

Also, technically the ssh 2.0 protocol does not enforce encryption and the like as it defines a "none" option which sends everything plaintext, however this module does not support that for several reasons.

To answer your questions:

1. I'm not sure what you're asking for here exactly. My misunderstanding may be partly due to me not knowing whether you're wanting to use this module as a client or a server. This module does not provide any kind of command line parsing on either end really, whether you're a client connected to a server trying to detect a `sudo` prompt for example, or if you're a server and you're accepting an interactive session and trying to parse client input.

2. This module uses the native TCP socket functionality built-in to node, so it's asynchronous/non-blocking -- you can do other things while ssh connections are open. However, the encryption/decryption is blocking, but node/iojs does not provide an API yet for doing crypto in the thread pool. Even if it did, I'm not sure if the overhead of have a crypto request go to the thread pool and back would make it worthwhile.

3. A pseudo-TTY is just what it sounds like. It's a "fake" terminal device allocated by the server so that a process executed on the server can display its output properly if it uses special escape sequences for purposes of formatting, layout, etc. The server module does not do this for you, so if you're writing a server and you receive a pty request, you must allocate a pty on behalf of the user in some way (e.g. via [`pty.js`](https://github.com/chjj/pty.js)). As far as Windows and pty usage goes, it kind of depends. If you're using the standard Command Prompt, it understands plain ANSI, so as long as you report your terminal as being "ansi", it should work fine. If you're using cygwin or some other third party command prompt, you might be able to get away with using a fancier terminal type.

4. It means exactly what it says. If an ssh client is trying to authenticate with a key, they can just send the public portion of their key first to verify with the server that the public key is allowed. Otherwise the client would have to compute a signature for the key, possibly to only find out that the key was not allowed in the first place. This could mean you end up sending two network requests (if the public key was accepted), but sometimes that's less overhead than having to waste CPU cycles calculating a signature.

5. Again, since I'm not sure what you'll be implementing, a client or server, it's difficult for me to answer this question correctly. If you're a server, you can write whatever you want. You could spawn a bash child process on the user's behalf and basically just pipe the two together, or you could have your own "shell". In fact, interactive sessions don't *have to* be shell sessions, for example see the [server-chat](https://github.com/mscdex/ssh2/blob/master/examples/server-chat.js) example in this repo.

**Comment by IngwiePhoenix** [comment]
> I'm a bit confused about your use case. Are you wanting to implement an ssh server? Are you using "REPL" to mean "command line interface" or are you actually looking for a real REPL over ssh?
> 
Yeah sorry - I am not a native english speaker. :) I really ment a REPL over ssh. And I am talking about a server implementation.

> Also, technically the ssh 2.0 protocol does not enforce encryption and the like as it defines a "none" option which sends everything plaintext, however this module does not support that for several reasons.
> 
> To answer your questions:
> 
> I'm not sure what you're asking for here exactly. My misunderstanding may be partly due to me not knowing whether you're wanting to use this module as a client or a server. This module does not provide any kind of command line parsing on either end really, whether you're a client connected to a server trying to detect a sudo prompt for example, or if you're a server and you're accepting an interactive session and trying to parse client input.
> 
What i ment is, when the client enters something on their end and sends it, which event fetches it? Or in other words, how do I get the stuff that the user types in, during an interactive session

> This module uses the native TCP socket functionality built-in to node, so it's asynchronous/non-blocking -- you can do other things while ssh connections are open. However, the encryption/decryption is blocking, but node/iojs does not provide an API yet for doing crypto in the thread pool. Even if it did, I'm not sure if the overhead of have a crypto request go to the thread pool and back would make it worthwhile.
> 
Good. Sounds like I’m better off when delegating this particular part to its own worker process, just to be sure.

> A pseudo-TTY is just what it sounds like. It's a "fake" terminal device allocated by the server so that a process executed on the server can display its output properly if it uses special escape sequences for purposes of formatting, layout, etc. The server module does not do this for you, so if you're writing a server and you receive a pty request, you must allocate a pty on behalf of the user in some way (e.g. via pty.js <https://github.com/chjj/pty.js>). As far as Windows and pty usage goes, it kind of depends. If you're using the standard Command Prompt, it understands plain ANSI, so as long as you report your terminal as being "ansi", it should work fine. If you're using cygwin or some other third party command prompt, you might be able to get away with using a fancier terminal type.
> 
I have seen pty.js being used to construct a Terminal in the browser - never thought it would be usable from within Nodejs. Thanks for the explanation, that helped :)

> It means exactly what it says. If an ssh client is trying to authenticate with a key, they can just send the public portion of their key first to verify with the server that the public key is allowed. Otherwise the client would have to compute a signature for the key, possibly to only find out that the key was not allowed in the first place. This could mean you end up sending two network requests (if the public key was accepted), but sometimes that's less overhead than having to waste CPU cycles calculating a signature.
> 
Ohh…thinking about it, that makes sense! Rather the 2 requests than the computations.

> Again, since I'm not sure what you'll be implementing, a client or server, it's difficult for me to answer this question correctly. If you're a server, you can write whatever you want. You could spawn a bash child process on the user's behalf and basically just pipe the two together, or you could have your own "shell". In fact, interactive sessions don't have to be shell sessions, for example see the server-chat <https://github.com/mscdex/ssh2/blob/master/examples/server-chat.js> example in this repo.
> 

I looked at the server-chat example and it got me a bit distracted trying to understand what Blessed was doing there…which also got me lost which events were for what, since the part in which the client screen is rendered is almost as long as the code with that substracted. :) That is why I am asking. I hoped to learn the answers from that code, but isntead it got me confused and that is why I decided to opent his issue.


All that is left to know which events to listen for for 1) - but the rest I can understand now and I am shaping up an idea for my implementation. Thanks for explaining these things to me so far! :)

Kind regards, Ingwie

**Comment by mscdex** [comment]
When you accept a shell (interactive) or exec request, a Channel stream is returned. This is what you read/write from/to. There is an example of accepting an exec request [in the readme](https://github.com/mscdex/ssh2#server-examples), but it's a similar thing for shell requests. The difference between the two is mostly just semantics.

**Comment by mscdex** [comment]
Closing this for now, if you have any specific issues/questions/concerns with the latest version of `ssh2`, let me know.
