### ISSUE TITLE
createReadStream much slower than exec('cat file')

### ISSUE THREAD

**Issue by maboiteaspam** [mscdex/ssh2#268]
Hi,

I found during my tests that ```sftp.createReadStream(someFile)``` is much slower than implementing ```conn.exec('cat someFile')```.

It s 3 times slower.

For 17 Mb the results are : 
- readUsingAStream 11980 ms
- readUsingExec 3807 ms

It s surprising, besides that, it s not a bug!

To reproduce I suggest to see this script
https://github.com/maboiteaspam/ssh2-utils/blob/master/test-large-files.js

BTW, i have also been able to segfault nodejs while doing a cat on a file created with data from 
```'dd if=/dev/urandom of=/home/vagrant/sample.txt bs=1M count=1',```

**Comment by mscdex** [comment]
Yes, it definitely is slower. The reason is that it performs 1 read at a time. The implementation is copied almost exactly from node core's fs.ReadStream/fs.WriteStream implementations.

You're better off using `sftp.fast{Get,Put}()` if you are writing to/reading from your local filesystem because those methods do parallel reads/writes.

About the "segfault": can you open a new issue if it is actually an exception being thrown? Otherwise if it's an C++ assertion, v8 crashing, or an actual segmentation fault, there's probably not much I can do about that. For an issue like that you may need to open an issue on node's issue tracker.

**Comment by maboiteaspam** [comment]
Ok thanks for the explanations. Crystal clear once again.

In my case i want to stream the file, also want to apply sudo on it. I have another method to realize fastGet / fastPut.

For the segfault let s see if i can sort out to trace it in a reasonable amount of time.

**Comment by maboiteaspam** [comment]
Unreasonable amount of time has passed since that i raised this issue. Closing it for now, as anyway, i m satisfied by this lib.
