### ISSUE TITLE
'close' callback fired before last 'data' callback?

### ISSUE THREAD

**Issue by polytypic** [mscdex/ssh2#324]
I'm having an issue where the output stream obtained via conn.exec sometimes (not always) fires the 'close' callback before the last (and only) 'data' callback.  Is this expected behaviour?

**Comment by mscdex** [comment]
Can you provide a reproducible example of this?

**Comment by VesaKarvonen** [comment]
Not really.  I can reproduce this quite reliably in our actual test and production environments (which I unfortunately cannot provide) and I have managed to reproduce it, with great difficulty, a couple of times with the following program:

```js
var Client = require('ssh2').Client;

function loop(commands, i, conn) {
    conn.exec(commands[i], function(err, stream) {
        var state = 0;
        if (err) throw err;
        stream.on('close', function(code, signal) {
            if (state !== 0)
                console.log('BUG');
            state = 1;
            if (i+1 < commands.length) {
                loop(commands, i+1, conn);
            } else {
                conn.end();
                start(commands);
            }
        }).on('data', function(data) {
            if (state !== 0)
                console.log('BUG');
            //console.log(data.toString().trim());
        });
    });
}

function start(commands) {
    var conn = new Client();
    conn.on('ready', function() {
        loop(commands, 0, conn);
    }).connect({
        host: '10.9.8.76',
        port: 22,
        username: 'vagrant',
        password: 'vagrant'
    });
}

var commands = [
    "git -C Repo ls-files --others --exclude-standard",
    "git -C Repo ls-files --modified",
    "git -C Repo ls-files --deleted",
    "git -C Repo rev-parse --abbrev-ref HEAD",
    "git -C Repo branch -r",
    "git -C Repo rev-parse --abbrev-ref --symbolic-full-name @{upstream}",
    "git -C Repo ls-remote --get-url",
    "git -C Repo rev-list --count HEAD..@{upstream}",
    "git -C Repo rev-parse --short HEAD",
    "git -C Repo log -p HEAD -s -1"
];

start(commands);
```

and a basic local vagrant box

```
Vagrant.configure(2) do |config|
  config.vm.network "private_network", ip: "10.9.8.76"
  config.vm.box = "ubuntu/trusty64"
end
```

with `git` installed and a git repository under `Repo` directory.

After starting the program (`node above-program.js`) I ssh to the vagrant box (interactively from terminal) to make some timing noise and do e.g. `git gc --aggressive` or `git pull` in the `Repo` several times and get `BUG` output if I'm _very_ lucky.  It is not essential that the same git repository is being accessed.

In our actual test and production environments, which are not just local vagrant boxes, the same bug is being triggered (fairly easily).  I doubt that the issue has anything to do with the particular commands being run.

Currently I'm working around this issue by essentially delaying the action after close by 20ms (effectively `setTimeout` in `close`), which seems to be enough to ensure that the last data callback is received before the collected output is processed.

**Comment by mscdex** [comment]
Can you try the master branch? I may have already fixed this, as there had been a previous report of data being cut off.

**Comment by VesaKarvonen** [comment]
I tried the master branch.  Didn't notice any difference.

**Comment by steelbrain** [comment]
I ran into a similar extremely difficult to reproduce bug that happens randomly, you execute the same command in a setinterval and it'll bug once every few seconds. In that bug, the `close` event is never fired but the data events are fired correctly

**Comment by steelbrain** [comment]
Disregard comment above, it was a problem in my code. so I am not hitting this exact same issue now

**Comment by chopj** [comment]
I'm seeing a very similar issue.  Close is being called before the final data call.

**Comment by mscdex** [comment]
Unfortunately I'm still not able to reproduce the problem. If anyone can manage to come up with more reproducible examples I would greatly appreciate it.

**Comment by coreyp1** [comment]
This code is a bit simpler to follow.  It runs the same command (`echo ~root`, which prints the root user's home directory location) 15 times.  Comments (and my output) after the code.

```javascript
var Client = require('ssh2').Client;

function loop(i) {
  if (i > 0) {
    conn.exec("echo ~root", function(err, stream) {
        if (err) throw err;
        stream.on('close', function(code, signal) {
          console.log('Close ' + i);
          loop(i - 1);
        }).on('data', function(data) {
          console.log('Data ' + i);
        });
    });
  }
  else {
    conn.end();
  }
}

var conn = new Client();
conn.on('ready', function() {
    loop(15);
}).connect({
  host: '<server ip or domain name>',
  port: 22,
  username: '<username>',
  privateKey: require('fs').readFileSync('<private key file>'),
  keepaliveInterval: 10000,
  readyTimeout: 10000
});
```

My output is the following:

```
Data 15
Close 15
Close 14
Data 14
Data 13
Close 13
Data 12
Close 12
Close 11
Data 11
Data 10
Close 10
Data 9
Close 9
Data 8
Close 8
Data 7
Close 7
Data 6
Close 6
Data 5
Close 5
Data 4
Close 4
Data 3
Close 3
Data 2
Close 2
Data 1
Close 1
```

In this case, numbers 14 and 11 are out of order.  It's different every time.  Once it was just number 3.  Another time everything was just fine.

This happened with 0.4.13.  I ran it on a Digital Ocean droplet ($5/mo., the cheapest).

**Comment by coreyp1** [comment]
For the sake of anyone else that is looking at this issue, my workaround is to use a ```setImmediate()``` in the 'close' stream event:

```javascript
function loop(i) {
  if (i > 0) {
    conn.exec("echo ~root", function(err, stream) {
        if (err) throw err;
        stream.on('close', function(code, signal) {
          setImmediate(function() {
            console.log('Close ' + i);
            loop(i - 1);
          });
        }).on('data', function(data) {
          console.log('Data ' + i);
        });
    });
  }
  else {
    conn.end();
  }
}
```

As for why I chose this approach, I'm assuming that this problem is a race condition between the 'close' and 'data' stream events.  That is, I'm assuming that the 'close' event and the 'data' event are both waiting in the event queue, but due to some unknown race condition, sometimes the 'close' event is earlier in the queue than the last 'data' event.

In my solution (workaround), the 'close' event uses ```setImmediate()``` to add an anonymous function on the event loop, so that any "sensitive" code will not run until the anonymous function is executed.  The event loop itself processes waiting events in an explicit order: first it processes Timer events, followed by I/O events, then lastly Immediate events, so this approach should ensure that the intended 'close' code (inside the anonymous function) is not executed until after the still-waiting 'data' event is processed.

**Comment by coreyp1** [comment]
I created a debug log of the connection.  As previously stated, the bug is difficult to reproduce reliably, which is why I assume that it is a race condition somewhere.  I'm running the Node.js code on a virtual machine on my laptop & connecting to a Digital Ocean droplet, if that matters.

I used the code from [my earlier comment](https://github.com/mscdex/ssh2/issues/324#issuecomment-171037484), but added `console.log` as the debug function in the server connection.  I looped the code 45 times, but only 26 and 21 failed.  I did not include the entire log, but from the "Close 28" (the very last console.log of 28, meaning that none of 28's logs are actually included) down to "Close 24".  27, 25, & 24 processed correctly, and I include them for comparison against the errant 26.  I did not include 21, because it was the same order as 26.

[Here is the log.](https://gist.github.com/coreyp1/eaaa457ca632a9b93d8c)

"Close 26" is most definitely in the wrong place, but I haven't been able to track down the reason.  I've been crawling through the code for this module as well as several of the related dependencies ("ssh2-streams" and "readable-stream"), but I'm not having any luck so far.

**Comment by mscdex** [comment]
Hrmm... does [this patch](https://gist.github.com/anonymous/e4db1b442765066211e4) or something similar help at all?

**Comment by coreyp1** [comment]
Sorry for the delay, I've been travelling for the last 2 weeks.

This patch absolutely fixed the problem!  Thanks!  I ran my example code 2000 times.  Without the patch, it will error on average every 25 calls.  With the patch, however, it did not error at all.

**Comment by mscdex** [comment]
@coreyp1 Thanks for the feedback.

@polytypic Can you confirm the patch works for you as well?

**Comment by polytypic** [comment]
I've moved on from the project, and don't have access to the production environment, but I sent an email to the maintainers.  Maybe they can verify whether the issue has been fixed.  Thanks at any rate!

**Comment by mscdex** [comment]
@polytypic Ah ok, thanks for the response. I am confident it solves the same issue so I will go ahead and push the change up.
