### ISSUE TITLE
Set an timeout on exec

### ISSUE THREAD

**Issue by alinex** [mscdex/ssh2#339]
I open a ssh connection to run a command using exec() on the remote server. But if this process runs longer than 3 Minutes (which may be the case) I want to get an timeout and cancel  further execution.

Is this possible in any way? 
Or how can I cancel a running task from the calling routine if I implement the timeout there?

**Comment by mscdex** [comment]
I think a `setTimeout()` whose callback calls `stream.close()` should work.

**Comment by alinex** [comment]
Thanks, that sounds reasonable and i'll try it tomorrow and give some feedback here.

**Comment by minesworld** [comment]
It isn't possible to set a general timeout as this would be a violation of the ssh2 specs which simply don't include such a thing. The server might be under heavy load etc. and forking a new child simply needs more time.

So it is clearly your decision if such a long time is an error or not and depends on your application logic.

Please close this issue.

**Comment by mscdex** [comment]
Another suggestion (assuming that you haven't closed stdin) is to send `\x03` to the stream. That *should* trigger SIGINT. If you're using a server other than OpenSSH (or one based on it), there might also be support for the explicit `stream.signal()` method.

**Comment by mscdex** [comment]
Or the brute force method: kill the process via a separate `exec()` using `kill <pid>` directly or perhaps something like `pkill`.

**Comment by alinex** [comment]
i tried to send an `\x03` - not working, neither the stream.close/end events are comming nor the process is being stopped

Do you have an example, how to send a signal to a process in another way?

And to kill the process in another exec call i need the `pid`, how to get it from the `conn.exec()` call?

**Comment by mscdex** [comment]
There's at least a couple of ways using the extra `exec()` solution:

* Background the process (may not be suitable) and echo the pid for use with `kill`. This will require some extra work because you have to parse the pid from stdout. For example: `exec('my actual command & fg', ...)`. This trick will background the process, print the job id and pid, and then immediately foreground the process.

* Use `pkill` to kill/signal the process by the original command string (either partial or exact match and/or other criteria)

**Comment by alinex** [comment]
Thanks, with the first tip it worked, getting the pid with `sleep 300 & fg' i get the pid and can use `kill -p` on it.

**Comment by alinex** [comment]
I also found the remote server handling to be an very easy solution:

    timeout 5 sleep 300

This will start a sleep for 300 seconds but stops after 5 seconds by sending a SIGTERM.

**Comment by mscdex** [comment]
Awesome. Glad to hear it's working for you!

**Comment by soichih** [comment]
I am running a command like this.

```
conn.exec("cd /somedir && somecommand")
```

The "somecommand" expects current directory to be set where I have config / input data, etc, so I need to "cd" to a directory before running it.

`cd /somedir` sometimes gets stuck, unfortunately, when there is an issue with underlying filesystem. I can't add timeout command before cd, because it's a shell command..

Like.. following won't work.
```
timeout 5 cd /somedir && timeout 600 somecommand
``` 

I think the best way to cleanly handle the timeout issue is by ssh2/conn.exec() to have the timeout capability implemented natively - or make stream.close() to work somehow? 

Can we reopen this issue?

**Comment by soichih** [comment]
I've found a possible workaround..

Although I stream.close() won't work, I can still do conn.end() to terminate all sessions - including the one that's stuck. If the cost of terminating all existing channel is less than the whole app getting stuck, then one could do something like following.

```
    var conn = new Client();
    ...
    var timeout = setTimeout(()=>{
        logger.error("reached connection timeout.. closing the whole ssh connection");
        conn.end();
    }, 1000*60);
    conn.exec("./myapp", (err, stream)=>{
        stream.on('close', (code, signal)=>{
            clearTimeout(timeout);
            if(code === undefined) console.error("timed out");
            if(code) console.error("app returned error", code);
            else console.error("success");
        });
    });
```

If someone knows a better workaround, please let me know!

**Comment by mscdex** [comment]
There is no foolproof method that can be done from the client side, short of the suggestions I already made earlier in this issue.

If you want to use the `timeout` Linux utility, you'd have to wrap your entire command string most likely because 'cd' is built into the shell and is not an external command.
