### ISSUE TITLE
Connections can fail, can't set StrictHostKeyChecking=no or UserKnownHostsFile=/dev/null on a connection

### ISSUE THREAD

**Issue by Stormwind99** [mscdex/ssh2#356]
Many VM providers re-use IP addresses for dynamically created and destroyed VMs while creating new host keys for each VM.   Without being able to StrictHostKeyChecking=no or UserKnownHostsFile=/dev/null on a connection it will fail with due to the StrictHostKeyChecking (new host key does not match host key in known_hosts).

**Comment by mscdex** [comment]
What does this have to do with the `ssh2` module? This module neither reads any files from disk nor does it spawn the OpenSSH client as a child process.

This module auto-accepts all hosts by default (see the `hostVerifier` config option), so that particular problem should not be an issue. If you are encountering some other connection problem, you may need to elaborate a bit and/or post debug output as a result of setting `debug: console.log` in your connection config object.
