### ISSUE TITLE
Not able to catch 'error' in ssh2 connection on MacOSx/Linux

### ISSUE THREAD

**Issue by komab** [mscdex/ssh2#364]
```
var Connection = require('ssh2');
this.connection = new Connection(); //ssh2 connection
        async.waterfall([function(callback) {
            // some initialization code to connect
            }
        }], function(err, opts) {
            if (err) {
                callback({
                    message: 'Error during connecting to the device...',
                    detail: err
                }, false);
            } else {
                console.log('Connecting to ... ' + JSON.stringify(self.info));
                self.connection.on('ready', function() {
                    console.info('Connected... opening a shell...');
                    callback(null, true);
                }).on('error', function(err) {
                    console.error('Error during connecting to the device: ' + err);
                    callback({
                        message: 'Error during connecting to the device...',
                        detail: err
                    }, false);
                }).on('end', function() {
                    console.info("Connection ended...");
                }).on('close', function(hadError) {
                    console.info("Connection closed..." + (hadError ? " with error" : ""));
                }).connect(opts);
            }
        });
```
Referring to the above code, I am connecting to a device using an ssh2 connection, everything works fine..I am getting console logs for on 'ready', on 'close' ,etc but not able to get the console logs when an on 'error' occurs.

I can capture the on 'error'event on win7 32 bit but not on MacOSx(10.9.5) or on Linux(Ubuntu 12). The on 'error' event is triggered when I forcefully end the connection to the device(say plug out the lan cable from my system).

Is this some limitation on Mac/Linux w.r.t the ssh2 module or is it that I am doing something wrong in the way to capture an error.

Any pointers will be really helpful.

node js version v0.10.29 ssh2 version v0.4.8

**Comment by mscdex** [comment]
Can you show the exact error you're seeing? Does it occur after you've started the shell? If so, did you attach an `error` event handler on the shell stream?

**Comment by komab** [comment]
I do not get any error in the console as such, it just doesnt seem to enter `` function(err, opts) { ``

**Comment by mscdex** [comment]
If that's the case, then the problem would be in your initialization code in your `async.waterfall()` functions since that would mean `connection.connect()` is not being called (since it is inside your `function(err, opts) {}` callback).

If instead what you mean is that you're not seeing an `error` or `close`/`end` event after abruptly disconnecting your network connection, then that is because keepalive packets are not sent by default (just like the OpenSSH client). To enable that, you need to set the `keepalive*` options described in [the documentation](https://github.com/mscdex/ssh2#client-methods).

**Comment by komab** [comment]
Thanks @mscdex  for your quick response, really appreciate it. My case is the latter which you described, I would need to set the keepalive options. Any recommended values ? But isn't it strange that everything works on windows and not on mac/linx ?

**Comment by mscdex** [comment]
The TCP keepalive settings used by OS differ from platform to platform and even within the same platform because for example, all *nix operating system users can tune the kernel TCP keepalive probe settings which can affect when the OS reports dead connections to userspace processes. Although these kernel-level settings typically aren't changed much because the typical default of long timeouts allow for unreliable network links between the client and server.

The application-level ssh keepalive settings depend on your needs and your application really, so there really are no "recommended values." You may need to experiment a bit to find what works best for your use case.

**Comment by komab** [comment]
Thanks using keepaliveInterval I was able to trap the error now in Mac/Linux :)
