### ISSUE TITLE
Synchronous code

### ISSUE THREAD

**Issue by zhulduz** [mscdex/ssh2#373]
Hello, developers.

I have some big problem. I use ssh2 and terminal js(hterm.js) library for rendering a stream.
My work is locked always, when I use such commands as ```seq 10000```, ```ls -R```. As I understand (I have looked at profiles) methods ```SSH2Stream.prototype._transform()```, ```parsePacket()``` make locks all work because of they have synchronous code.

Thanks in advance.

**Comment by mscdex** [comment]
I don't understand your question.

**Comment by zhulduz** [comment]
I mean that this methods are synchronous (without any optimization). If I use additional js-library for rendering stream (hterm.js) and I call commands such as ```ls -R```,  ssh2 locks all work.

**Comment by mscdex** [comment]
I'm not sure I understand yet... can you provide a simple, minimal code example along with what you're expecting vs. what you're seeing/experiencing?

**Comment by zhulduz** [comment]
My english is bad, I will try to describe problem more clearer. I have been making ssh client, for this I use ssh2 and hterm libraries. Both are written in javascript.
Here my code:
```js
Client = require('ssh2').Client
client = new Client()
client.on 'ready', () ->
    client.shell terminal.io, (err, stream) ->
        if err
            _error_messages err.message
            return
        stream.on 'close', () ->
            client.end()
        .on 'data', (data) ->
            terminal.io.print data.toString()
        .stderr.on 'data', (data) ->
            terminal.io.print data.toString()
```
When I started to test, I found problem with commands ```ls -R```, which locked the stream output.
I can see you a profile:

![screen shot 2015-12-14 at 11 17 53](https://cloud.githubusercontent.com/assets/1921276/11773448/04fdf370-a24c-11e5-9576-f732d0bfba82.png)

**Comment by mscdex** [comment]
Do you have a small project that I can run that reproduces the problem?

Also, can you point to where you are getting this hterm library? The only one I could really find was the one on npm, written by the Chromium team, that is for the browser.

If hterm is buffering data, the problem might be that you're trying to print too much data to the hterm terminal too quickly? When you listen for `data` events manually like that, there is no backpressure handling going on, so `ssh2` will keep emitting data. For situations like this, the proper way is to create a real node.js stream that you can pipe to so that backpressure is all handled automatically. I'm not sure that hterm provides a standard writable node.js stream.

**Comment by zhulduz** [comment]
I think we should talk about execution time is spent by ssh2.

**Comment by mscdex** [comment]
I'm always open to pull requests to improve performance, but there's not much I can do right now without a reproducible example that I can run locally.
