### ISSUE TITLE
socket.setKeepAlive() doesn't get initialDelay

### ISSUE THREAD

**Issue by zhulduz** [mscdex/ssh2#389]
Hi, everyone!

Could you please clarify why in a code structure 
```javascript
sock.on('connect', function() {
    debug('DEBUG: Client: Connected');
    self.emit('connect');
    self._sock.setKeepAlive(true);
    if (!cfg.sock)
      stream.pipe(sock).pipe(stream);
  })
```
 we don't pass 'delay' parameter in a method  seck.setKeepAlive().

Thanks a lot.

**Comment by mscdex** [comment]
The default value of the `initialDelay` should be adequate enough. We don't really depend on TCP keepalive for detecting connection status (because the OS TCP keepalive settings are typically use very long timeouts), but it's enabled anyway just in case the OS should notify us first before our own dead connection detection mechanism does.

**Comment by zhulduz** [comment]
As far as I understood, you always set ```initialDelay = 0``` and ```enable = true```, 
https://github.com/mscdex/ssh2/blob/master/lib/client.js#LC204
https://nodejs.org/api/net.html#net_socket_setkeepalive_enable_initialdelay

But I think you should provide a way to customize these parameters.
Why do you think that these default values are adequate enough?

**Comment by mscdex** [comment]
The reason is that the process is still at the mercy of the OS for other keepalive parameters (e.g. `tcp_keepalive_intvl` and `tcp_keepalive_probes` on Linux) and we can already send application-level keepalive probes, which is what OpenSSH already can do to detect dead connections, not just relying on TCP keepalive.

**Comment by mscdex** [comment]
Closing this for now since as previously mentioned, application-level keepalive gives you the best control over detecting dead connections.
