### ISSUE TITLE
.shell and .exec expects 'data' callback even if you don't need it.

### ISSUE THREAD

**Issue by laodc** [mscdex/ssh2#412]
So on 0.4.x version. i could call
`conn.exec( cmd, function( e, s ) { s.on( 'close', function( code, signal ) { /* do things */ } ); } );`

and it would work as expected, but on 0.5.x it appears not i have to do
`conn.exec( cmd, function( e, s ) { s.on( 'data', function( d ) {} ); s.on( 'close', function( code, signal ) { /* do things */ } ); } );`
just so that the close event can occur, leaving me with a lot of empty event triggers (I don't need the data that is returned)

Was this a planned feature from 0.4 to 0.5 ?

**Comment by mscdex** [comment]
This is expected and is actually a bug *fix* which I have just now added a note about in the wiki.

The problem is that users were listening for `close` and surprised to see `data` events being emitted *after* `close` was emitted (due to a race condition and the order of protocol messages sent by the server).

So you will need to add something like `stream.resume(); stream.stderr.resume();` to ignore the data.

**Comment by laodc** [comment]
Thanks for the quick feedback.
