### ISSUE TITLE
auto reconnect feature

### ISSUE THREAD

**Issue by laodc** [mscdex/ssh2#413]
Is it possible while in sftp, that if a connection error occurs ('[Server: Failure]' for example), that a re-connection can be attempted (with number of retries and timeout) so it can attempt to resume what it was doing?

**Comment by mscdex** [comment]
IMHO this kind of higher-level feature is something best left to other modules to implement when building on top of `ssh2`.

**Comment by laodc** [comment]
Hmm, I assumed it would be a lower-level to be handled by ssh2 as it just detects the connection lost and reconnect if settings state so, otherwise error like it currently does.

Leaving it to something outside of ssh2 i'm not sure how it handles current code execution and handling. but i'm still getting my head around node's event based logic, so who knows...

**Comment by mscdex** [comment]
FWIW a third party module should be able to implement this by simply listening for an `error` event on the connection object and then just calling `.connect()` again.

**Comment by laodc** [comment]
Hmm, I just guessed it seemed overkill as a 3rd part module for something i assume to be built-in.

But I understand.

**Comment by mscdex** [comment]
You don't *have* to create a third party module just for *that*, but I meant a third party module that is already building on top of `ssh2`. If you're using `ssh2` directly you should be able to do just what I suggested (listening for `error` and reconnecting).

**Comment by gsimko** [comment]
I'm wondering if there's a recommended pattern for implementing such a functionality.
The error triggering a reconnect event works fine for keeping a valid client around, but if the client is used between the error and reconnection, those calls will be erroneous. @mscdex do you know any libraries that implement a retry logic that automatically hides these complications from users? That is, for example if I made an sftp.fstat call which failed because the client is already disconnected, it would automatically make the client.sftp().open().fstat() calls to rebuild the connection.
