### ISSUE TITLE
Connection hopping

### ISSUE THREAD

**Issue by deppli** [mscdex/ssh2#454]
![image](https://cloud.githubusercontent.com/assets/10197277/17204859/78ea6e30-54da-11e6-81a5-3c011c922cfa.png)
Connection hopping must use the nc command?

**Comment by mscdex** [comment]
It's not a requirement, but you need something that can relay the socket data. `nc` is just one common utility that does just that.

**Comment by deppli** [comment]
In my company, you must ssh to the  jump server and on the jump server you can ssh to the online machine. what can I do?

**Comment by mscdex** [comment]
That's exactly what the connection hopping example is showing. netcat connects to the real destination and `ssh2` uses that netcat stream as the underlying connection to the real destination.

**Comment by deppli** [comment]
I know , but what can I do for  relay the socket data without the nc command?

**Comment by mscdex** [comment]
Is it not available or what is the problem?

**Comment by deppli** [comment]
I no permission to use nc command

**Comment by mscdex** [comment]
You mean you get a permission denied error when calling `.exec('nc ...', function(err, stream) { /* err is set */ })`?

**Comment by michaelbushby** [comment]
I also have a similar issue, nc is not available on our gateway (not installed) but ssh is, so we ssh into the gateway and from there ssh to the next machine. Is there a way to do this with just ssh. 
aka ssh -t MachineA ssh MachineB

**Comment by mscdex** [comment]
You can use *anything* that can make a TCP connection and use stdin/stdout for writing to/reading from the connection. You could use `nc`/`netcat`, `socat`, Perl, node, bash (if TCP support was compiled in), or whatever else.

I just use netcat in the example because that's usually available on every system.

If your server supports it, you could also use `conn.forwardOut()` to request an outbound connection to the destination host. Both methods will work. I chose `conn.exec()` for the example because that's usually enabled in most ssh server installations, whereas initiating outbound connections may not.

**Comment by mscdex** [comment]
Closing this for now, as I previously mentioned there are multiple ways to go about this. If none of those options will work for you, then you won't be able to do connection hopping (using that server).
