### ISSUE TITLE
SFTP: low speed in uploading

### ISSUE THREAD

**Issue by eidosam** [mscdex/ssh2#459]
Hi,

I'm trying to use **ssh2** replacing the current used method (spawn'ing sftp command)
It is 10times slower!
The files used in this case 450MB *3 + 150MB *1
Uploading in parallel limit:4

```js
ssh2 = require('ssh2').Client;
/*
file: instance of Google Cloud Storage File 
https://googlecloudplatform.github.io/gcloud-node/#/docs/google-cloud/0.38.3/storage/file
*/
uploadFile = function(file, opts, cb) {
  var ssh2Conn, gcsReadStream, fileName;
  ssh2Conn = new ssh2();
  fileName = _.last(file.name.split('/'));
  gcsReadStream = file.createReadStream();
  gcsReadStream.on('error', function(e) {
    cb(e);
  });
  ssh2Conn.connect(opts.connectionCfg);
  ssh2Conn.on('ready', function() {
    console.log("Connection with SFTP server " + opts.connectionCfg.host + " is established");
    ssh2Conn.sftp(function(err, sftp) {
      var pathOfDestinationFile, sftpWriteStream;
      if (err) {
        cb(err);
      } else {
        pathOfDestinationFile = opts.path + "/" + fileName;
        sftpWriteStream = sftp.createWriteStream(pathOfDestinationFile);
        sftpWriteStream.on('open', function() {
          console.log("File " + sftpWriteStream.path + " uploading started");
        });
        sftpWriteStream.on('finish', function() {
          console.log("File " + sftpWriteStream.path + " uploaded successfully");
          sftpWriteStream.end();
          sftp.end();
          ssh2Conn.end();
        });
        sftpWriteStream.on('error', function(err) {
          console.log("Error at " + sftpWriteStream.path + ", " + err);
          cb(err);
        });
        gcsReadStream.pipe(sftpWriteStream);
      }
    });
  });
}
``` 

any hints?

Regards!

**Comment by mscdex** [comment]
This is known and is why `sftp.fastGet()`/`sftp.fastPut()` exist. You should use those unless you really need a node stream object.

**Comment by eidosam** [comment]
Thanks for quick reply, you are right indeed, I used node stream because I'm reading from GCS, not local file.

**Comment by mscdex** [comment]
If you are able to manually do multiple, parallel reads from GCS for a single file, then you could try to implement a `sftp.fastPut()`-like function. You could look at the source code for that function and use it as a guide/reference if you want to see one way to accomplish the parallel reads/writes.

Another solution which may/may not be feasible is to have the destination server pull down the file directly from GCS so that the traffic doesn't have to go through a middle system. I'm not familiar with GCS, but it would be something like:

```js
ssh.exec('curl -L https://gcs-server.example.org/myfile > /path/to/save/file',
          (err, stream) => {
  /*..*/
});
```
instead of using `sftp.*` to transfer.
