### ISSUE TITLE
Killing exec'd process without ending the connection

### ISSUE THREAD

**Issue by aashidham** [mscdex/ssh2#475]
I would like to kill a `bash` process that I exec'd without ending the connection. However, it doesn't always respond to ctrl-D or ctrl-C, or any of the POSIX signals, because sometimes I am running vim on that bash process, or another program that takes in that input and interprets it in different ways. The server also seems to ignore the POSIX signals. The only general solution to this currently is something hacky like this: http://stackoverflow.com/questions/22164570/sending-a-terminate-ctrlc-command-in-node-js-ssh2 but there has to be a better way.

**Comment by mscdex** [comment]
As far as I know there is no elegant and reliable solution for that, unless you want to grab the pid in a different way by performing a `pgrep` or similar via a separate `exec()`.

**Comment by aashidham** [comment]
In that case, all the more reason to add this feature to your library. It
seems like a pretty key feature to any ssh client. In Terminal.app on OSX,
for example, removing one ssh console terminal window doesn't terminate all
other ssh connections to that server on other windows. How do desktop
clients implement this?

**Comment by mscdex** [comment]
I don't think it's as easy as you're making it out to be because of all of the differences in remote servers and operating systems. It'd be very difficult to create that kind of (reliable) abstraction when it does not already exist at the protocol level.

I do not know of any desktop clients that handle this explicitly. Most clients would probably just close the channel/connection, which may or may not kill running processes.

**Comment by aashidham** [comment]
Any updates on implementing this?

**Comment by mscdex** [comment]
My comments still stand, there's not much that can be done by this module.

**Comment by gbaumgart** [comment]
+1
