### ISSUE TITLE
HTTP Proxy

### ISSUE THREAD

**Issue by uxsoft** [mscdex/ssh2#484]
Hi,

We're sitting behind a company proxy. I've seen how to configure this to work with SOCKS proxy. Is there any way we can configure this to go through HTTP proxy?

Thanks

**Comment by mscdex** [comment]
Which do you mean, tunneling http requests through an ssh connection, or vice versa?

**Comment by uxsoft** [comment]
I want to connect to an sftp server, but im sittiny behind company proxy:)

**Comment by mscdex** [comment]
If your http proxy supports the `CONNECT` method and any destination port, then you could follow the [example](https://nodejs.org/api/http.html#http_event_connect) from the node documentation to perform that kind of request. If successful, the http request object will emit a `'connect'` event with a socket object that you can pass directly to `ssh2` via the `sock` property in `connect()`.

If your http proxy supports the `CONNECT` method but only specific ports (e.g. 80 or 443), then you will probably need to either set up some kind of intermediary server *or* your destination ssh server will need to run on one of those ports.

If your http proxy doesn't support the `CONNECT` method, you will definitely need to use some sort of intermediary http/https server that tunnels the ssh traffic via a special http `GET` or other request.

**Comment by uxsoft** [comment]
My proxy supports CONNECT, but only a specific port (8080). 

Could you please provide any guidance on how to set up the intermediate server?

Thanks a lot.

**Comment by mscdex** [comment]
That's really beyond the scope of this module.

However if your are in control of the ssh server, you could change it to listen on port 8080 and use the first solution I mentioned.

If you aren't in control of the ssh server, then you will need some kind of secondary http proxy (e.g. squid) that you control, which will permit unrestricted (port-wise) `CONNECT` requests. Then it's just a matter of connecting to the first proxy, issuing a `CONNECT` request to the secondary proxy. Once you have the socket object for that first proxied request, send another `CONNECT` request (this time to the server and port of the destination ssh server) over that socket (using a custom [`http.Agent`](https://nodejs.org/docs/latest/api/http.html#http_class_http_agent). Then when you get the socket from *that* secondary proxied request, pass that as `sock` to `ssh2`'s `connect()`. Because of the amount of proxying going on here, do not expect the best latency and/or speed.

**Comment by lmdc45** [comment]
Just a note as I was trying to do this as well using ssh2

To connect though a http proxy you can (where c is your ssh2 Connection object, obj is your ssh2 connection options and using async/await):


```
import http from 'http';

function getSocketProxy(path){//return socket as a promise
    // Make a request to a tunneling proxy
    let res = new Promise((resolve,reject)=>{

      let options = { //change host and port to your own http proxy settings
        port: 1337,
        host: 'localhost',
        method: 'CONNECT',
        path
      };
  
      const req = http.request(options);
      req.end();
  
      req.on('connect', (res, socket, head) => {
        console.log(res.statusCode);

        resolve(socket);

      });
      
    });
    return res;
}

async function main(){
  let path = obj.host + ':' + obj.port;
  obj.sock = await getSocketProxy(path);
  c.connect(obj);
}
main();
```

Can do the same with socks proxy:

```
import pkg from 'socks';
const { SocksClient } = pkg;

async function getSocks5(path){ //return socket through socks promise
  const { port, hostname } = new URL(`http://${path}`);
  const options = {
    proxy: {
      host: 'localhost', // ipv4 or ipv6 or hostname
      port: 1080,
      type: 5 // Proxy version (4 or 5)
    },
   
    command: 'connect', // SOCKS command (createConnection factory function only supports the connect command)
   
    destination: {
      host: hostname,
      port: Number(port)
    }
  };

  const info = await SocksClient.createConnection(options);
  return info.socket;
}
async function main(){
  let path = obj.host + ':' + obj.port;
  obj.sock = await getSocks5(path);
  c.connect(obj);
}
main();
```
