### ISSUE TITLE
angular2

### ISSUE THREAD

**Issue by candidature** [mscdex/ssh2#490]
Hi,

Is there a angular2 version of this? I tried to use it but it gives too many errors.

Thanks,
-Pankaj

**Comment by mscdex** [comment]
You can't use `ssh2` directly in the browser because there are generally no TCP sockets and other low-level features available in the browser.

You can however use `ssh2` on the backend (via node of course) and have a frontend that communicates with the backend over something like socket.io or plain websockets. For an example of such a web terminal, see [this StackOverflow answer](http://stackoverflow.com/questions/38689707/connecting-to-remote-ssh-server-via-node-js-html5-console/38690242#38690242).
