### ISSUE TITLE
shell canot send command to remote linux

### ISSUE THREAD

**Issue by IsLLiu** [mscdex/ssh2#492]
I have one connection,then to run command again after stream close, sometime it run very perfect,but sometime it canot run the command.only show 
<pre>
192.168.2.199 close.
stdout: Last login: Fri Nov  4 00:07:19 2016 from 192.168.2.209

stdout: [root@localhost ~]#
</pre>
the command I send is: `cd /home/ll/Desktop/test/linux\nmake clean\nmake\nexit\n`
this is the code:
```js
var that = this;
that.conn.shell(function(err, stream){
  if(err){
    then(true, null);
  }else{
    var buf = '';
    stream.on('data', function(data){
      buf = buf + data;
      console.log('stdout: ' + data);
    }).stderr.on('data', function(data) {
      console.log('stderr: ' + data);
    }).on('close', function(){
      setTimeout(function () {
        then(false, buf);
      });
    });
    stream.write(cmd);
    stream.end();
  }
});
```
can u help me ?

**Comment by mscdex** [comment]
There are a few immediate issues I see here:

1. The main issue is that the shell probably isn't ready for input as soon as the shell session is started. During this period input may be ignored instead of buffered. Have you tried delaying your `stream.write()` in some way, such as until you see your *first* `'data'` event on the `stream`?

2. Your `'close'` event handler should be on the `stream` object and not on `stream.stderr`.

3. `stream.end()` for shell sessions is usually not very useful and could cause problems such as truncated output from the shell.
