### ISSUE TITLE
ssh2 transfert speed is SLOW.

### ISSUE THREAD

**Issue by FunkyGOK** [mscdex/ssh2#531]
I have almost finished an application with ssh2, though I am finding that the transferts time is 2-3 times longer than sftp or lftp in the command line. Is there any way I can improve my tranferts speeds.
I have made to test files one using fastPut and the other using createWriteStream. They basically transfert my test file in the same time.
Thank you for any help. 

<img width="648" alt="sftp_createwritestream" src="https://cloud.githubusercontent.com/assets/11753278/23208678/36338656-f8f6-11e6-93a8-b918efae0e9a.png">
<img width="695" alt="sftp_fastput" src="https://cloud.githubusercontent.com/assets/11753278/23208679/3655f31c-f8f6-11e6-976b-19f130520c06.png">

**Comment by mscdex** [comment]
The `sftp.fast*()` methods are about the best you can do, and keep up to date with `ssh2`/`ssh2-streams`. Those methods use parallel reads/writes (and similar chunk sizes) just like the OpenSSH sftp client.

**Comment by soichih** [comment]
Can we re-open this ticket? I believe there is a real performance issue with sftp() even when compared to a single threaded streaming via ssh2. 

With my test case, the transfer speed goes up by factor of 1.5 - 3 if I simply replace ssh2.sftp with ss2.exec("cat > /remote/path"). I believe exec() streams data on a single channel. I believe there is something wrong with the implementation of sftp() or how it interacts with nodejs stream.

**Comment by mscdex** [comment]
There is going to be some overhead because SFTP is another protocol on top of SSH. However, as previously stated, `sftp.fast*()` will always be faster than `sftp.create*Stream()` because of concurrency.

**Comment by soichih** [comment]
I can't use sftp.fast* because my data has to stream without first being stored on disk. fast* can only read/write from disk.

What I was pointing out though, was that the ssh2 sftp is slow not because of the single threded-ness. If I switch to use exec("cat ...") approach, which uses a single threaded transfer model also, it could be up to 400% faster than sftp. I believe this means it is possible to do some performance optimization with sftp code.

**Comment by mscdex** [comment]
@soichih I'm open to reasonable PRs to improve SFTP performance.

**Comment by gitmors** [comment]
Good day,

I have exactly the same problem as described here. I am also trying to stream files over sftp from one server to another. 

```
const rs = sftp.createReadStream(remotePath);
const ws = sftp2.createWriteStream(localPath, attributesCopy);

rs.pipe(ws)
    .on('close', () => {
})
```

I believe also there is something wrong with the implementation of sftp() or how it interacts with nodejs stream.
Maybe you still have an idea how to solve this problem.

Thank you very much for any help.

**Comment by gitmors** [comment]
Possibly we could now re-open this ticket. [claytongulick](https://github.com/claytongulick) Please let us know your config option.

**Comment by bforgacs** [comment]
Hi there, same issue here and can confirm it's still relevant. Using version `9.1` as of now.
So the deal is we need a read stream as we must transform 50-100-200GB sized files on the fly, and upload them continuously into a Google Cloud Storage bucket. Obviously it would be unreasonable to store such huge files temporarily, also, we cannot let the process to take more time it should. That's why `fastGet` is simply not an option for us.

According to our recent measurements we have had a read speed of somewhere around 1Mbit/s regardless of where the SFTP is. We measured locally running containerised SFTP and production grade running SFTP as well. Both provided the same exact result.
