### ISSUE TITLE
How to connect to docker throw ssh

### ISSUE THREAD

**Issue by burnoutx** [mscdex/ssh2#539]
Hi !

Im having some troubles to connect to docker machine, anyone can take a look and guide me, I think i have a mesh between ports and hosts.

I have an instance in Amazon AWS which could be accessed by ssh on port 22, inside this machine I have a docker with mongodb inside.

I can connect without problems from a mongo GUI (MongoChef)

Here is the amazon data

> host: ec2-XXX-0-113-25.compute-1.amazonaws.com
> port: 22
> user: ec2-user
> key: key.pem

And here docker details

> image: mongo
> ip: 172.17.0.2
> port: 27017

and here the code Im trying to do this

    var Connection = require('ssh2');
    var conn = new Connection();

    function onReady() {
         console.log('Tunneling ready');

        conn.forwardOut('172.17.0.1', 27017, '127.0.0.1', 27017, function(err, stream) {
             if (err) throw err;
             stream.on('close', function() {
                 console.log('TCP :: CLOSED');
                 conn.end();
             }).on('data', function(data) {
                 console.log('TCP :: DATA: ' + data);
             }).end();
        });
    }

    conn.connect({
         host: 'ec2-XXX-0-113-25.compute-1.amazonaws.com',
         port: 22,
         username: 'ec2-user',
         privateKey:require('fs').readFileSync('./key.pem'),
         readyTimeout: 99999,
         debug: console.log
    });

     conn.on('ready', onReady);

Thanks for your help !

**Comment by mscdex** [comment]
`ssh2` does not perform automatic connection tunneling out of the box. You will need to handle that yourself or use a third party module that builds on top of `ssh2`. `forwardOut()` just sets up the remote connection, allowing you to read/write from/to it however you want.

On the subject of database modules, `forwardOut()` is especially handy for database modules that support arbitrary streams to be used as the underlying database connection instead of forcing a (new) TCP socket to be created for each connection. I am not sure if there are any mongodb modules that support this kind of feature, but for example the `mysql2` supports this.
