### ISSUE TITLE
Fail to log in when using multiple ssh keys stored in agent

### ISSUE THREAD

**Issue by mickaelperrin** [mscdex/ssh2#558]
Hi,

I experience some difficulties to authenticate when I use multiple ssh keys stored in my agent.

If I have only one key stored in the agent, it works well. As soon as I use multiple ssh keys, I get the error message:

````
    Error: Too many authentication failures for mickaelperrin
    at onDISCONNECT (/gulp/node_modules/ssh2-streams/lib/ssh.js:2197:15)
    at SSH2Stream.<anonymous> (//gulp/node_modules/ssh2-streams/lib/ssh.js:203:5)
    at emitMany (events.js:127:13)
    at SSH2Stream.emit (events.js:204:7)
    at parsePacket (/gulp/node_modules/ssh2-streams/lib/ssh.js:3742:10)
    at SSH2Stream._transform (/gulp/node_modules/ssh2-streams/lib/ssh.js:667:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/gulp/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
````
Note that `ssh` is working well event with multiple keys stored in agent, and I configured my `.ssh/config`with:

        Host *
           IdentitiesOnly yes

Should I specify some additionnal options in my `ssh_config` array, to get it working ?

Currently I use only:
   
     { 
       host: something,
       username: something,
       port: something,
       agent: process.env.SSH_AUTH_SOCK
     }

Thanks,

**Comment by mscdex** [comment]
There is no `IdentitiesOnly`-like support yet.

**Comment by mscdex** [comment]
You can implement this now by passing your own `authHandler` function (which determines which authentication method to try next) since `ssh2` v0.7.1.

**Comment by dkebler** [comment]
@mscdex can you illuminate a bit more on the form of this handler?  

From the docs looks like that's just for handling a typical progression not for trying another key in the agent when one fails but rather trying the agent when  `Password -> Private Key` fail.   As it is now it tries one that fails and then gives up even though another key in the agent will work.  This is not the case with the openssh client.  It tries all keys in the agent until one works (or fails completely) without having to say anything about what key in the agent will work.

e.g.
```
Host nas
   user sysadmin
   hostname nas.domain.net
```
`ssh nas` works even though there are two keys in the authorized_keys file and the same two in my agent and I know one won't work because it was set only for using with rsync and not a login shell via openssh client.

-----------

authHandler - function - Function with parameters (methodsLeft, partialSuccess, callback) 

where methodsLeft and partialSuccess are null on the first authentication attempt, otherwise are an array and boolean respectively. Return or call callback() with the name of the authentication method to try next (pass false to signal no more methods to try). 

Valid method names are: 'none', 'password', 'publickey', 'agent', 'keyboard-interactive', 'hostbased'. Default: function that follows a set method order: None -> Password -> Private Key -> Agent (-> keyboard-interactive if tryKeyboard is true) -> Hostbased

**Comment by mscdex** [comment]
@dkebler This issue was about `IdentitiesOnly`, which skips any ssh-agent usage at all and only uses individual private key files. Technically this could have been implemented/handled equally well before `authHandler` was introduced (just simply make sure `agent` is unset in the `connect()` config object), but `authHandler` gives more control and allows you to override that `agent` if it is set.
