### ISSUE TITLE
Long running shell response data truncated

### ISSUE THREAD

**Issue by cfsbhawkins** [mscdex/ssh2#559]
So I have written an SSH client, that executes commands on a remote server, a few of the calls grab and parse JSON logs, some of these logs can be very large. It seems that the larger logs keep stoping at the same point. I have tried the on('readable' function()) option for chunking, but it still stops at the same point. Am I missing a setting somewhere where I could set a very large buffer size so I don't loose this data?

```
My Client 
  let sshConn = new SSHClient();
  sshConn.on('ready', function () {
    sshConnected = true;
    sshConn.shell(function (err, stream) {
      if (err) throw err;
      stream.on('close', function () {
        sshConnected = false;
        sshConn.end();
      })
        .on('data', function (data) {
          parseSSHData(data);
          //process any queued up commands 
          if (sshCommands.length > 0) {
            stream.write(sshCommands.shift());
          } else {
            commandExecuting = false;
          }
        })
        .stderr.on('data', function (data) {
        })
      shell = stream;
    });
  })
    .connect({
      host: XXXXX,
      port: 22,
      username: SSH_USER,
      privateKey: require('fs').readFileSync('./rsa_key')
    });
};
```

**Comment by mscdex** [comment]
This is a common issue that many people run into with streams. The key thing to remember is to never assume the size of chunk sizes coming from a stream. So you will either need to process the stream in chunks or buffer the data in some way.

Also on an unrelated note, `.shell()` is not the best candidate for executing individual commands because you both lose information (e.g. no stdout/stderr differentiation, no indication of whether the process died due to signals, etc.) and you complicate output handling because of output from the shell itself (e.g. shell prompts). Use `.exec()` instead where possible, which does not have these problems.
