### ISSUE TITLE
Couldn't canonicalize: Operation unsupported / Need cwd

### ISSUE THREAD

**Issue by tony-kerz** [mscdex/ssh2#560]
> disclaimer: i'm kind of an s/ftp noob

i'm trying to use the "sftp-only" server example from the readme, and i'm getting this after passing authentication
```
Couldn't canonicalize: Operation unsupported
Need cwd
```
the example only implements on `OPEN`, `WRITE` and `CLOSE`.

does basic connection from a client require additional operations maybs?

any guidance appreciated!

> i'm using the default `sftp` client on osx `10.11.6` to connect

**Comment by mscdex** [comment]
I'm betting it's probably sending a realpath request to determine cwd, so you'd need to implement that request.

There is no such thing as a "basic connection" because different clients can behave differently. However, for file uploading, open, write, and close are pretty much required no matter what.

**Comment by tony-kerz** [comment]
thanks @mscdex, i added:
```
              .on('REALPATH', (reqid, path) => {
                dbg('realpath: reqid=%o, path=%o', reqid, path)
              })
```
and it got called and that error went away, but the client just kind of hangs:
```
sftp -P 2222 -F /dev/null -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile=/dev/null' partner-1@localhost
Warning: Permanently added '[localhost]:2222' (RSA) to the list of known hosts.
partner-1@localhost's password:
Connected to localhost.
```
i'm sure it's cause i haven't provided a viable implementation for `REALPATH`, but i guess i miss understood the package a little bit, it just provides like a "scaffolding" of an sftp server and consumers of `ssh2` have to provide implementations for every event?

i was looking for a node based alternative to [prodftpd](http://www.proftpd.org/) which includes behavior on operations, but which is also configurable with a plugin model (e.g. with their sql plugin, it can authenticate users from a relational and configure their home directory to use for put/get operations).

i'm getting this is lower level package, are you aware of anything that is built on top of `ssh2` that fleshes out more function of an sftp server? or if it is relatively straight forward, do you have a reference of such an implementation?

regards,
tony

**Comment by mscdex** [comment]
Yes, the reason it's hanging is because it's waiting for a response. You will need to read the sftp documentation in the `ssh2-streams` repo on what responses are expected for which events.

If you want something higher level, you will just need to search on npm. For example, a quick search reveals [this module](https://github.com/BriteVerify/node-sftp-server) that you might try, or at least use as a guide.

I am not aware of any complete, product/standalone-like solution like proftpd that is written in pure javascript.

**Comment by Silverutm** [comment]
> I'm betting it's probably sending a realpath request to determine cwd, so you'd need to implement that request.
> 
> There is no such thing as a "basic connection" because different clients can behave differently. However, for file uploading, open, write, and close are pretty much required no matter what.

Could you provide an example on how to do this, I have read the documentation but I couldn't understand it

**Comment by 131** [comment]
Maybe you can take a look at https://github.com/idjem/ssh2-sftp-server, a simple & working sftp server implementation (that reads & writes files)
