### ISSUE TITLE
[Question] About: ssh-public-key authentication example code

### ISSUE THREAD

**Issue by developer94404** [mscdex/ssh2#561]
Hi, my question is about this Server example code for public key authentication:

    else if (ctx.method === 'publickey'
             && ctx.key.algo === pubKey.fulltype
             && buffersEqual(ctx.key.data, pubKey.public)) {
      if (ctx.signature) {
        var verifier = crypto.createVerify(ctx.sigAlgo);
        verifier.update(ctx.blob);
        if (verifier.verify(pubKey.publicOrig, ctx.signature))
          ctx.accept();
        else
          ctx.reject();
      } else {
        // if no signature present, that means the client is just checking
        // the validity of the given public key
        ctx.accept();
      }

Why would you have the else block that calls ctx.accept(), even if the signature is not present. 

Isn't the signature required to be present *and* correctly verified, in order to ctx.accept() the client?   

Does the above sample code mean that any client submitting a public key that matches the stored public key in the example, can get authed into the server, regardless of the signature they actually generate from their private key?

Thanks for your help, in advance.

**Comment by mscdex** [comment]
The comment says it all, if there is no signature, the client is just checking to see if the key is valid or not. The reason for this is that signatures are relatively expensive to compute, so there is no sense wasting cycles on a signature for a key that will get rejected anyway because the server does not know about it.

**Comment by developer94404** [comment]
Thank you for the kind reply and info. There must be something I am not understanding (my apologies): in production code, I don't think you would actually allow the else{ ctx.accept() }, right?  Otherwise, I could just have my SSH client send the example server, those public keys, and it will still be accepted, even if I don't own the private keys to generate a real signature ?

**Comment by mscdex** [comment]
When you `ctx.accept();` when there is no signature you're *only* telling the client, 'this public key is valid.' You are not actually authenticating them because that requires a signature. The non-signature public key check is obviously optional (it's the client's benefit to not compute a signature for an unknown key) and not all clients may send it.

**Comment by developer94404** [comment]
Ah, I see. That explains it perfectly. That was exactly what I was not understanding. Many thanks again for your kind help and replies.

**Comment by axkibe** [comment]
Thanks, that had me confused as well.
