### ISSUE TITLE
When calling exec() and telling it to use a pty, no stderr is returned

### ISSUE THREAD

**Issue by finger563** [mscdex/ssh2#597]
All stdout / stderr gets sent to stdout.

**Comment by mscdex** [comment]
That's more or less to be expected due to how a pty/tty works. The OpenSSH and other clients/servers behave the same way. A pty/tty only has one output (e.g. a monitor, serial port, etc.), so there really is no way to differentiate between stdout and stderr (except possibly at the application level).

**Comment by finger563** [comment]
Yea, right now I'm doing it at the application level sadly, but thanks for the info!
