### ISSUE TITLE
remove colour formatting codes 

### ISSUE THREAD

**Issue by hanct** [mscdex/ssh2#599]
Is there a way for ssh2 to remove colour formatting codes which comes from the remote server?

**Comment by mscdex** [comment]
You'll have to explain a bit more. Where are you seeing them and what do they look like?

**Comment by hanct** [comment]
The remote server (ubuntu) returns color formatted data back to the ssh2 client when I do a ls command.
I was thinking if ssh2 has any filter to filter it away.
The  red-colored Hello world text returned from ubuntu will look something like this:  "\e[31mHello World\e[0m"

**Comment by hanct** [comment]
I am looking into the Pseudo-TTY settings for ssh2

By default, term  is set to  'vt100'.  May i know what are the other possible values? Maybe by changing other value, my application using ssh2 will not get color information.

**Comment by mscdex** [comment]
Are you using `.shell()` or otherwise using a pty (e.g. `.exec(..., { pty: true })`)? If so, that may be why. Alternatively, you can try explicitly setting the `term` option to whatever terminal name you want to use that doesn't support colors. Otherwise as a last resort, you can tell `ls` to automatically determine color behavior via `--color=auto` which should do the right thing (assuming no pty is being used).

**Comment by hanct** [comment]
Horray, it works.  I just do

.shell( {pty: true,term:'dumb'} ,.....).  And it works.

Thanks mscdex.
