### ISSUE TITLE
Writing binary data using createWriteStream

### ISSUE THREAD

**Issue by hubetier** [mscdex/ssh2#625]
This is in fact not really an issue.

I am trying to send a binary file via sftp using ssh2. Problem is, that the data is stored as utf8.
Here is the code i am using:

          let readStream = new Readable();
	  readStream.setEncoding('binary');
            readStream.push(fileContent);
            readStream.push(null);
            let writeStream = sftp.createWriteStream(ftpInfo.remote.baseDir + fileName,{ flags: 'w', encoding: null});
            writeStream.on('close', function() {
                  sftp.end();
                }
            );
            readStream.pipe(writeStream);
          });

I have no idea what i am doing wrong. Any help welcome.

**Comment by mscdex** [comment]
You don't have to create a stream just to write to a file when you already have the entire file contents in memory. Just use `sftp.writeFile()` (like node's `fs` API):

```js
sftp.writeFile('/path/to/remote/file', fileContent, function(err) {
  // check `err`
});
```

**Comment by mscdex** [comment]
@AlesMenzel No, parent paths are not created automatically, unless of course the server decides to do that automagically (but I would not expect any server to do this due to the magical nature).

If you wanted, you could `ssh.exec('mkdir -p /parent/path/for/file', ...)` beforehand if you have permission to execute commands and not just SFTP access.

**Comment by matusbielik** [comment]
@mscdex 

> You don't have to create a stream just to write to a file when you already have the entire file contents in memory. Just use `sftp.writeFile()` (like node's `fs` API):
> 
> ```js
> sftp.writeFile('/path/to/remote/file', fileContent, function(err) {
>   // check `err`
> });
> ```

is this method available? I can't find it anywhere, in documentation nor in the codebase. It would be really handy as fastPut throws Permission denied when I try to overwrite files.

**Comment by mscdex** [comment]
@matusbielik The `ssh2` documentation links to the SFTP API documentation, which is [here](https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md). However, if you're getting a 'Permission Denied' error, I don't think using a different SFTP API function is going to help since the underlying problem (wrong file permissions) will still exist and both `fastPut()` and `writeFile()` use the same SFTP commands under the hood (e.g. open file for writing, write data, close file).

**Comment by matusbielik** [comment]
@mscdex you were right, the problem was on the server side. Thank you for your quick response!

Anyway, I couldn't find any mentions about `writeFile()` in the link you've provided.

**Comment by mscdex** [comment]
Probably a documentation issue then. The goal is to mirror node's `fs` API, so generally you can reference that as well.
