### ISSUE TITLE
Client.on('ready') event trigger two times.

### ISSUE THREAD

**Issue by HW-Siew** [mscdex/ssh2#627]
I am trying to run some command after client is connected to server. I noticed that 'ready' event was triggered two times. Any idea what could be wrong? 

Thanks

```js
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.exec('some_command', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
  host: '192.168.100.100',
  port: 22,
  username: 'frylock',
  privateKey: require('fs').readFileSync('/here/is/my/key')
});
```

**Comment by mscdex** [comment]
You just posted the example in the readme. This example does not reconnect, so it is not possible for `'ready'` to be emitted more than once. Can you share the actual code you're using instead (obscuring passwords if necessary)?

**Comment by HW-Siew** [comment]
Hi, thanks for the reply. The following is the code i am using. This sshConnect function does the connection and execute command(cmd) for every call. Some of the commands i tried works fine, but not the other which result in two logs of 'ready run' & 'exec run'. As a consequence, the stream.on('close') captured two logs as well, one for code=0 and one for code=undefined.

```
function sshConnect(cmd){
	return new Promise(function(resolve, reject) {

		conn.on('ready', function() {

			console.log('ready run')
			
			conn.exec(cmd, function(err, stream) {

    			if (err) reject(err);

    			var stdout = Buffer.concat([]);
    			var stderr = Buffer.concat([]);

    			console.log('exec run')

			    stream.on('close', function(code, signal) {

			    	console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
			    	if(!parseInt(code)){
			    		// when code = 0
			    		resolve(stdout.toString());
			    	}else{
			    		// when code != 0
			    		reject(stderr.toString()); 
			    	}
			    	
			    	conn.end();
			    }).on('data', function(data) {
			    	
			    	stdout = Buffer.concat([stdout, data]);
 	
			    }).stderr.on('data', function(err) {

			    	stderr = Buffer.concat([stderr, err]);

			    });
  			});
			 
		})
		.on('error', function(err){
			reject(err);
		})
		.connect({
  			host: 'xx.xx.xx.xx',
 			username: 'user',
			privateKey: require('fs').readFileSync('./key/priv.key') ,
  			port: 22,
		});
	})

}
```

**Comment by mscdex** [comment]
Some issues that are apparent here:

1. You're using the same Client object (`conn`) across `sshConnect()` invocations. This is why you're seeing previous `'ready'` (and probably other) event handlers fire each time you call `sshConnect()` -- the event handlers are never removed. My advice: just create the new Client object inside your function to avoid this problem.

2. `if (err) reject(err);` should be `if (err) return reject(err);` or similar to avoid continued execution of the rest of the function.

3. `if(!parseInt(code)){` can lead to unexpected results when the process is killed due to a received signal or other reasons. In those cases, `code` will be null/undefined and that will cause that conditional to evaluate to `true`. This is similar to node's child process's `'exit'`/`'close'` event.

**Comment by HW-Siew** [comment]
Hi @mscdex, thank you so much for the advises! very much appreciated. I will test the change soon and update/close accordingly.

Thanks again. :D
