### ISSUE TITLE
ssh2 shell return socket hang up after afew second

### ISSUE THREAD

**Issue by calvinlcz** [mscdex/ssh2#628]
I am trying to start an interactive shell to one of the remote host, command entered in the shell seems to return output from the Ubuntu terminal not the remote host and this hanged up after a few second. The exact idea of this is to start communication using shell and upon terminated, it will return back to the web application. Please advice where could be wrong. Thanks.

```js
router.post('/shell', function(req, res){
      shell(server, function(err, result){
            if(result)
                res.send(true);
      }
}

function shell(server, callback){
	var Client = require('ssh2').Client;

	var conn = new Client();
	conn.on('ready', function(){
		console.log("Client:: ready");
		conn.shell(function(err, stream){
			if(err) throw err;
			stream.on('close', function(){
				console.log("Stream :: close");
				conn.end();
				callback(null, true);
			}).on('data', function(data){
				console.log('STDOUT: ' + data);
			}).stderr.on('data', function(data){
				console.log('STDERR: ' + data);
			});
		});
	}).connect({
		host: server.hostAddr,
		port: server.hostPort,
		username: server.userName,
		privateKey: require('fs').readFileSync('/here/is/my/key')
	});
}
```

**Comment by mofux** [comment]
If you are only interested in the output of a particular command, you should use `conn.exec` instead of `conn.shell`. `conn.shell` will provide you with an interactive stream to the remote shell that you can write commands to, and get the output from. This stream will only close if you terminate the remote shell process, for example by sending the exit command to the remote shell via `stream.write('exit\n')`. Please see the Readme.md for a more detail on how to use `conn.shell`.
