### ISSUE TITLE
cp -rf  No such file or directory ？

### ISSUE THREAD

**Issue by SilenceDN** [mscdex/ssh2#632]
conn.exec('cp -ru /home/d-repo/fore-repo/* /home/yszz-t/plugin/htdocs/.res/dst',()=>{
.....
})
could not successfully execute this command by ssh2 . error:
```
bash: cp -ru /home/d-repo/fore-repo/* /home/yszz-t/plugin/htdocs/.res/dst: No such file or directory
```
but it successfully in Xshell 
```
[root@iZwz9aehttqhroz4p0xw9zZ dst]# cp -ru /home/d-repo/fore-repo/* /home/yszz-t/plugin/htdocs/.res/dst
[root@iZwz9aehttqhroz4p0xw9zZ dst]# 
```

Why

**Comment by mscdex** [comment]
I don't know, `ssh2` is just the middleman here. Does it work if you use `.shell()` and `stream.write()` your command to the interactive shell instead of `.exec()`? If that works, then there may be something being run during shell startup that is affecting things. If it doesn't work, I don't really know what else to suggest.
