### ISSUE TITLE
ssh2 raises dependency issues

### ISSUE THREAD

**Issue by badhya** [mscdex/ssh2#673]
While complilation time it raises error as below:
Failed to compile.

Error in ./~/ssh2/lib/agent.js Module not found: Can't resolve 'dns'  in '<path>\node_modules\ssh2\lib' 

Tried modifying webpack config file by including:
node: {
dns: ‘empty’,
dgram: ‘empty’
},
externals: [
               ‘child_process’
]

Failed to compile.
 
Error in ./~/ssh2/lib/agent.js Module not found: Can't resolve 'child_process' in '<path>\node_modules\ssh2\lib' 
 
@ multi (webpack)-dev-server/client?http://localhost:8088 webpack/hot/dev-server ./~/react-dev-utils/webpackHotDevClient.js ./src/js/index.js

But even this doesn't help.

Tried removing the node_modules directory and re-installing the fresh packages, even that din’t help much.

I'm currently using node 6.11.5 and webpack 2.7.0

Also upgraded node to 8.10.0 but no progress.

Please if you could suggest a workaround or point out if I'm missing any requirements

**Comment by mscdex** [comment]
As this is a webpack issue (not an issue with `ssh2`), I would suggest submitting this to the [webpack issue tracker](https://github.com/webpack/webpack/issues) instead.

If you're trying to use this module from a browser, it's not possible because of the requirement of low-level functionality like plain TCP connections, child processes, etc.
