### ISSUE TITLE
Proper use of sftpStream.on('REALPATH') and sftpStream.name

### ISSUE THREAD

**Issue by P4sca1** [mscdex/ssh2#697]
First of all, thank you for your work on this very useful package!

I'm currently trying to create my own sftp server, which raised some about the `REALPATH` event.
As far as I know, it should return the location with symbolik links, as well as references to `/./`, `/../` expanded. Does it need to begin or end with a `/`?
Basically, is this code enough?
```
        sftpStream.on('REALPATH', (reqId, location) => {
          const realPath = fs.realpath(location);

          return sftpStream.name(reqId, [{
            filename: realPath,
            longname: `drwxrwxrwx 1 foo foo 3 Dec 8 2009 ${realPath}`,
            attrs: {}
          }]);
        });
```

Another thing I don't get is the `longname`. In the documentation it states, that it is equal to the output of `ls -l`, but in every implementation I find hardcoded values dating to 8.12.2009.

Also, how does SFTP use the `REALPATH`? Is there any documentation on it and the other methods (`READDIR`, `OPEN`, ...)?

EDIT:
I came across another problem. Is there any example on how to list the current content of a directory? I saw some implementations, which use handles and buffers. Is there any documentations on this?

**Comment by P4sca1** [comment]
Alright, that makes it clear. 

> I came across another problem. Is there any example on how to list the current content of a directory? I saw some implementations, which use handles and buffers. Is there any documentations on this?
Any more info on this?

**Comment by mscdex** [comment]
Listing the contents of a directory is at the very minimum an `OPENDIR` followed by one or more `READDIR`s, and then a `CLOSE`. Is that what you're asking?

**Comment by P4sca1** [comment]
Should be enough info for me to get it running. Thank you for your fast answers!

**Comment by P4sca1** [comment]
Okay, there are still some things unclear for me. I hope you can help me out.
When there is an `OPENDIR` operation, I create a handle which is referenced in future `OPENDIR` and `CLOSE` operations for example, to know which directory should be read or closed.
However, I don't know what I should actually return to the client as the handle. I know that it should be a buffer, but what should be the content of the buffer? (I never worked with buffers yet, so it is quite new for me and I don't quite get the concept of Buffers yet).
Also, when is the `CLOSE` operation called? My guess would be on client disconnect (to remove all handles to opened directories) but what about open files? When is the `CLOSE` operation called?

**Comment by mscdex** [comment]
> However, I don't know what I should actually return to the client as the handle

You return any binary data blob you want that will be used to reference the opened directory. Obviously it needs to be unique amongst any other open handles, so that you know which handle is which for further requests. For getting directory contents, if you're using a third-party binding to `opendir()` and other related POSIX calls, then you can simply just write the file descriptor number to a Buffer and send that to the client. Then just read the number back from the Buffer sent by the client to know what the file descriptor is (making sure it's an fd they originally opened, and not just any fd open by your process) However, if you're simply using `fs.readdir()` to implement `READDIR` requests, you will need to come up with your own scheme since `fs.readdir()` does everything in one go.

In general, avoiding `fs.readdir()` is a good idea because bindings to POSIX `opendir()`, `readdir()`, etc. allow you to actually stream directory contents, whereas `fs.readdir()` returns the *entire* contents in one call, which could result in problems with *very* large directories. It's possible there are already bindings to the relevant libuv functions on npm somewhere. If not, it should not be hard to do if you've created a C++ node addon before.

> (I never worked with buffers yet, so it is quite new for me and I don't quite get the concept of Buffers yet

[Buffers](https://nodejs.org/docs/latest/api/buffer.html) are just objects representing binary data. They are very common throughout the node API.


> Also, when is the CLOSE operation called

Whenever the client is finished reading directory contents and wants to free up any resources associated with the open directory handle on the server.


> My guess would be on client disconnect (to remove all handles to opened directories)

Yes, that would be a good idea, otherwise you would have resource leaks on the server, but you should also clean up the appropriate resources when you receive a `CLOSE`.


> but what about open files

There is nothing different for files. You clean up any resources you have open for that particular handle. That could mean closing a backing file descriptor, removing the handle from the client's opened files/directories table/map, etc. `CLOSE` is used for both file and directory handles.

**Comment by P4sca1** [comment]
Very helpful andere, thank you very much!

> In general, avoiding fs.readdir() is a good idea because bindings to POSIX opendir(), readdir(), etc. allow you to actually stream directory contents, whereas fs.readdir() returns the entire contents in one call, which could result in problems with very large directories.

What's the benefit of streaming, I thought you can only send the whole directory content to the client, so no matter what you do, you need to wait for readdir to bei finished before sending the results. Or is it possible to send directory chunks to the client (e.g. Filezilla), so that the directory contents loading progess can be seen in the client in real time?

**Comment by mscdex** [comment]
> What's the benefit of streaming, I thought you can only send the whole directory content to the client, so no matter what you do, you need to wait for readdir to bei finished before sending the results

`fs.readdir()` internally does the equivalent of `opendir()`, followed by one or more `readdir()` calls until there are no more entries, and then a `closedir()`. By instead using the POSIX functions directly (or the libuv equivalent if you want to be cross-platform on the server side), you can not only stream the directory contents, but the requests can now match up with the underlying OS function calls (e.g. `opendir()` with `OPENDIR` requests, `readdir()` with `READDIR` requests, etc.).

So the benefits of doing a proper streaming of directory entries include:
* You are more closely mirroring the SFTP API (as I just described)
* You're avoiding issues with directories with large numbers of subdirectories/files/etc. that could not only take up a lot of memory but could result in delays with responding to the client request
* If the client is looking for a particular directory entry, they will be able to simply send `CLOSE` early if they find it, instead of having to receive additional directory entries that they do not care about



> I thought you can only send the whole directory content to the client, so no matter what you do, you need to wait for readdir to bei finished before sending the results. Or is it possible to send directory chunks to the client (e.g. Filezilla), so that the directory contents loading progess can be seen in the client in real time?

This is entirely dependent upon the client implementation. The *possibility* of the client showing directory contents incrementally is there though if the server implements proper directory contents streaming, but whether the client ends up showing the contents incrementally is up to them, and there may be valid reasons for them to buffer them first.

**Comment by P4sca1** [comment]
Sorry for opening this issue again, but I do have another question.
You said what using the POSIX functions directly has some benefits, which I understand.
However I don't really know how to call opendir() for example with node.js directly. Could you give me some advice on that?

**Comment by mscdex** [comment]
You'd have to either write your own bindings or find an existing addon on npm that provides them. Node does not currently expose those functions.
