### ISSUE TITLE
Referenced ssh2 package in the vue framework, the dependency package could not be found

### ISSUE THREAD

**Issue by navysummer** [mscdex/ssh2#701]
development environment：vue+vuex+webpack
vue code：
[1.txt](https://github.com/mscdex/ssh2/files/2025817/1.txt)

error：
Failed to compile.

./node_modules/ssh2/lib/client.js
Module not found: Error: Can't resolve 'dns' in '/home/navy/Desktop/ssh/node_modules/ssh2/lib'
 @ ./node_modules/ssh2/lib/client.js 3:16-30
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/HelloWorld.vue
 @ ./src/components/HelloWorld.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by mscdex** [comment]
If you're trying to use this in a browser, that won't work because some necessary functionality is not available there, such as performing dns requests and making plain TCP connections.

If you're trying to use this in an Electron or similar project, I can't really help there since I am not familiar enough with such projects. For those kinds of situations it's usually some kind of configuration issue either on webpack's side or Electron's.
