### ISSUE TITLE
how can I send a Control+C to server? help

### ISSUE THREAD

**Issue by mbossX** [mscdex/ssh2#704]
how can I send a Control+C to server?

**Comment by mscdex** [comment]
Write `'\x03'` to the stream. You may/may not need to have a pty activated for that to work though.

**Comment by mscdex** [comment]
How are you writing the character?

**Comment by ElectroDr3am** [comment]
`conn.shell(false, {pty: true}, function (err, stream) {
      if (err) throw err;
      stream.on('close', function () {
        console.log('Stream :: close');
         conn.end();
      }).on('data', function (data) {
        console.log('STDOUT: ' + data);
      }).stderr.on('data', function (data) {
        console.log('STDERR: ' + data);
      });
      stream.write('\x03')
    })
`
By the way it doesn't work as expected - login message appears and nothing happens on command input. 
What am I doing wrong? Ubuntu 16.04, Node.js v 8.9

**Comment by mscdex** [comment]
@ElectroDr3am It looks like you're mixing `shell()` and `exec()` usage here. Try dropping the first two arguments so that you just have the callback as the only argument to `shell()`.

> By the way it doesn't work as expected - login message appears and nothing happens on command input.

How are you sending commands?

Also, in general avoid `shell()` (and use `exec()` instead) unless you absolutely need it and are prepared to deal with the issues arising from such an interactive session (e.g. not knowing when a command finishes, what its exit code was, etc.). `shell()` is most useful for non-programmatic use, as if you're manually typing in commands at a terminal.

**Comment by ElectroDr3am** [comment]
Sorry! My mistake - messages dublicates cause using `nodemon`, using `node` works fine.
