### ISSUE TITLE
Getting authentication methods

### ISSUE THREAD

**Issue by toniov** [mscdex/ssh2#706]
Hi,

I'm creating a command line tool using this module. I'd like to mimic the behavior of the OpenSSH ssh client for the authentication part: This is not well documented, so I'm not sure, but I think the client tries the auth methods that the server give him back in a string (in a certain configurable order).

For example, I would like to prompt the user for a password only in case the method `password` is included in that string.

Is there a way to get that information from the server using this module?

Thanks in advance :)

**Comment by mscdex** [comment]
No, that information is ignored because it's not a reliable source from my experience. The list of authentication methods returned by the server during an authentication failure can literally be any comma-separated list the server wants to send. I've seen servers that don't advertise any list and I've even seen some servers that intentionally hide necessary and/or usable methods from that list.

**Comment by toniov** [comment]
Thanks for your reply.

Even if it's not reliable depending on the server, I think that being able to get that information can be useful in some cases. At least in case of a OpenSSH server, the accepted methods, specified in the `sshd_config` file, are added to that string by default.

Also, it's laid down in the [standard](https://www.ietf.org/rfc/rfc4252.txt):

> The 'authentications that can continue' is a comma-separated name- list of authentication 'method name' values that may productively continue the authentication dialog.

**Comment by mscdex** [comment]
You can now handle authentication method order via `authHandler` as of https://github.com/mscdex/ssh2/commit/fbea9a71b285a0a2591da6e4701d9181cd733366. This handler receives both 'authentications that can continue' as well as the partial success indicator.
