### ISSUE TITLE
What exactly is stream's stderr

### ISSUE THREAD

**Issue by twifty** [mscdex/ssh2#707]
Let me make it clear that I'm not very clear how the SHH protocol works. That's why I use a library like `ssh2`.

I'm using only the client side of the module to spawn a remote shell. All the examples have references to `stream.stderr`. Yet any output written to stderr, by a script on the remote machine, is merged into stdout. Now, I'm guessing that since a socket can only be written and read,  this is just the nature of SHH. A quick google search on the topic has really confused me.

What is this `stderr` intended to be used for? Is it meant to be used in conjunction with the included server (some form of IPC?) or is it for errors only on the local machine?

**Comment by mscdex** [comment]
Interactive shell sessions (`.shell()`) almost never have anything written to the stderr stream because they're designed to be used within a terminal, which only have one input (keyboard) and one output (display).

The stderr stream is more useful for command execution (`.exec()`), which is designed for more "programmatic" use, where you have separate stdout and stderr streams (much like node's `child_process.spawn()`).

**Comment by twifty** [comment]
Ok. I've refactored my code to use `exec` rather than `shell` and I can confirm separate streams for stdout and stderr.

Perhaps you could add a note to the README regarding stderr and the `shell` method. It would be helpful to those of us not familiar with SSH/process streams/pipes to know this in advance of using the method.
