### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by ElectroDr3am** [mscdex/ssh2#718]
Is it possible to make tab-like autocompletion like native ssh-clients have?

**Comment by mscdex** [comment]
(Continuing the discussion from #704)

I'm not sure what exactly you're trying to accomplish, but here is a simple example of an interactive shell session:

```js
const Client = require('ssh2').Client;

(new Client()).on('close', () => {
  console.log(':: Connection Closed');
}).on('ready', function() {
  console.log(':: Connection Ready!');
  this.shell({
    term: process.env.TERM,
    rows: process.stdout.rows,
    cols: process.stdout.columns
  }, (err, stream) => {
    if (err) throw err;

    stream.on('close', () => {
      // Don't let process.stdin keep process alive since we no longer need it
      process.stdin.unref();

      this.end();
    });

    // Connect local stdin to remote stdin
    process.stdin.setRawMode(true);
    process.stdin.pipe(stream);

    // Connect remote output to local stdout
    stream.pipe(process.stdout);
    process.stdout.on('resize', () => {
      // Let the remote end know when the local terminal has been resized
      stream.setWindow(process.stdout.rows, process.stdout.columns, 0, 0);
    });
  });
}).connect({
  // ...
});
```

Ctrl+C, tabbing, anything else will work just fine in this example because the raw input is being delivered to the remote end as-is without node getting in the way. This does have some implications though, such as the process not emitting `'SIGINT'` events and such, just so you are aware.

**Comment by ElectroDr3am** [comment]
Thanks a lot, it's just what I need! Spend 2 days to make `readline` work
like that.

вс, 22 июл. 2018 г. в 0:00, mscdex <notifications@github.com>:
