### ISSUE TITLE
sftp not working in Electron project

### ISSUE THREAD

**Issue by Kiyoaki-w** [mscdex/ssh2#723]
In my Electron-based project, while running the example as below, the sftp connection doesn't work.
The err message has been written in the code block.
I tested the code in Nodejs and it works with no error.

How to solve this problem? Thanks!

```js
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
  conn.sftp(function(err, sftp) {
    if (err) throw err; // here comes the problem and the err message is 'No response from server'
    sftp.readdir('foo', function(err, list) {
      if (err) throw err;
      console.dir(list);
      conn.end();
    });
  });
}).connect({
  host: '192.168.100.100',
  port: 22,
  username: 'frylock',
  password: 'nodejsrules'
});
```

**Comment by mofux** [comment]
I can tell from my own experience that it should work from electron in general. But I've also seen a problem like this before, where it would just timeout on the initial server connection over and over again - but after running a manual connection from the command line via `ssh <user>@<host>...` it would suddenly also start to work from electron (I'm on Mac). It's a bit mysterious to what could cause such a behaviour, maybe it's got to do with DNS cache, not sure...

**Comment by mscdex** [comment]
If you're getting an error message of 'No response from server' it means the connection went away. If you add a `'close'` event handler to your connection object, you should see it get called.

I'm not sure why it would work fine in node but not in Electron though. You might try with the latest Electron version if you aren't already, otherwise you might have better luck asking on the Electron issue tracker since the issue seems to be specific to their project?
