### ISSUE TITLE
call ssh.exec method was successful, but not correct execute my command

### ISSUE THREAD

**Issue by lk565434471** [mscdex/ssh2#725]
I'm sure I've been connected to remote server-side successful.
And I wrote a correct shell command "cd /home/liukai/version/20180815_1134_r193998_r193969/server && sh startup.sh stop". It works well on localhost. But when I use "ssh.exec" to try to execute this command. It can't work well. Cloud you help me with this problem?

**Comment by ashish00076** [comment]
Any progress with this issue?
Even I'm facing a similar problem.

I'm trying to execute a shell file(`.sh`) located on the remote server. I do obtain a connection successfully, but the control returns to the callback handler with `Exit Code [127]`.

Is it something like this module cant execute the command `sh filename.sh` over the server? 
If yes, what else could be done? Is there any other alternative?

Please suggest an alternative.


Regards,
Ashish Deshpande

**Comment by mscdex** [comment]
Usually if you look at what's being written to the `ssh.exec()`'s `stderr` stream you should see what's wrong. An exit code of 127 typically means a syntax error or similar in the script. It could be the shell being used is not what the script was written for (e.g. using `dash` on Ubuntu to execute a bash script that has features not supported by `dash`).

**Comment by OliverSG400** [comment]
Hi,
I also vote for this issue to be investigated.
I like this tool very much, and use it for some scripting, however, it is weird for me that manual operation and ssh.exec leads to different results. For instance:
`systemctl enable firewalld`
works as expected for manual ssh session, while from the scripted version it also works but causes an error with correct text in it. Like it should be regular output, but it passed through error stream and finished prematurely.
Also, I think it might be due to some thread splitting because making `yum -y update`, which may take up to 5 minutes for my case, I can see update process running in the background while my js script finished with error. So it works, but the script execution is cut.
Thank you in advance for taking a look! Your tool is brilliant :)

**Comment by mscdex** [comment]
@OliverSG400 You'll have to be more specific here, especially with regard to "correct text", what code you're using, what command you're using, and what the remote OS and version are.

For example, on Ubuntu 18.04, I can `ssh.exec('sudo systemctl enable foo')` that exits with a zero (success) status code with the text coming through stderr. This is exactly how it works with an interactive session. I verified this by performing the same command in an interactive session and redirecting stderr to /dev/null (as expected, I got no output as a result).

It's entirely possible that on some operating systems a TTY is required to use sudo, which `.exec()` does not use by default, although you can pass a config object to enable such a feature.

As far as `.exec()` exiting early, again, this depends on many variables here. For example, if you're listening for the `'exit'` event only, it could easily fire before the rest of the command's output is received -- this is just like with node child processes. Like node child processes, you should instead listen on the `'close'` event which fires not only after the process has exited, but also when there will be no more output.
