### ISSUE TITLE
Question: VPN example

### ISSUE THREAD

**Issue by amilajack** [mscdex/ssh2#731]
Can this library be used to make a VPN in node? If so are there any examples out there that anyone can point me to? Thanks in advance!

**Comment by amilajack** [comment]
I see. How come it isn't possible to implement a true VPN?

**Comment by mscdex** [comment]
One reason is that ssh is TCP-based, so passing packets as-is over TCP would result in performance issues, especially with TCP packets due to the way TCP congestion control works. This is why most VPN implementations use UDP or another protocol on top of the IP layer instead of TCP.

I'm also not entirely sure that iptables/tproxy supports redirecting raw (ethernet/IP) packets, so you'd have to set up a TUN interface which (to me) is a little more invasive.

**Comment by amilajack** [comment]
Oh okay that makes. Thanks! Do you have any suggestions for wrapping node http calls in a vpn?
