### ISSUE TITLE
Client shell repeats input

### ISSUE THREAD

**Issue by mcshaman** [mscdex/ssh2#761]
I can't work out how to implement an interactive client that could replace CLI ssh. I want to include an ssh npm script that will connect to my project web server as if I had just called `ssh username@hostname.com`. I am pretty close however I am not sure how to stop ssh2 repeating all inputs.

My script looks something like this:

```javascript
const {Client} = require('ssh2')

const connection = new Client()

connection.on('ready', () => {
	process.stdout.write('Client :: ready')

	connection.shell((pError, pStream) => {
		if (pError) {
			throw pError
		}

		process.stdin.pipe(pStream)
		pStream.pipe(process.stdout)

		pStream.on('close', () => {
			process.stdout.write('Client :: closed')
			process.exit()
		})
	})
})

connection.connect({
	host: 'hostname.com',
	username: 'username',
	password: '****'
})
```
After connecting to the server, every command I run is repeated in the shell before executed. e.g:

```
hostname$ pwd
pwd
/home/username
hostname$ exit
exit
```

**Comment by mscdex** [comment]
By default, local ttys always echo input. On the remote side, your input is echoed back to you for similar reasons (the pseudo-tty settings). You can disable one or the other, although I would suggest disabling local tty echo because especially for interactive sessions you will want to know just how much of your input the server has received.

For disabling local echo you can call `process.stdin.setRawMode(true)`. See [this example](https://github.com/mscdex/ssh2/issues/718#issuecomment-406823236) for a simple interactive shell using actual keyboard input.

**Comment by mcshaman** [comment]
Thanks for the prompt support!
