### ISSUE TITLE
How to catch such a event like "Are you sure you want to continue connecting (yes/no)"

### ISSUE THREAD

**Issue by Kisarigi** [mscdex/ssh2#779]
I connected a server with this ssh2,and it really worked.Then I tried to connect another server path through this server, so I writed this code : 
 `stream.write('ssh -c 3des-cbc  xxx@xxxx -p 22\r');`
then program OUTPUT is :
```
The authenticity of host 'xxx (xxx)' can't be established.
RSA key fingerprint is xxxxxx
Are you sure you want to continue connecting (yes/no)?
```
I wonder how to catch such a event and answer it, I tried to write like this : 
```
 "if(data.toString().search('authenticity')>0){
        stream.write('yes');
        console.log('OUTPUT: ' + data);
      }"
```
but it doesn't work.

**Comment by mscdex** [comment]
It's a stream, so you only get chunks, so you'd need to either buffer some amount of data or use some means to search a stream of data.

Or you could specify additional OpenSSH client options to prevent such prompts from displaying in the first place.

Or since you seem to be using a jump host to get to this destination server, you could `ssh2` directly for that. There is [an example of this in the readme](https://github.com/mscdex/ssh2#connection-hopping), however in that example you can typically replace the `exec('nc ...')` with a `forwardOut()` to remove dependence on external programs.

**Comment by Kisarigi** [comment]
@mscdex Got it, thank you!

**Comment by Kisarigi** [comment]
@mscdex  I'm sorry to bother you again... I can't find the explain about methods of `stream` at `readme.md`.
 Only in example there is  some methods such as `stream.stderr.on` ,but I don't know how to use it and  what can it do.  
Is there some explain about all the methods of 'stream' ?

**Comment by mscdex** [comment]
`stream` is a [`Channel`](https://github.com/mscdex/ssh2#channel) instance.

**Comment by Kisarigi** [comment]
@mscdex  Got it, thank you again!
