### ISSUE TITLE
Getting the authenticated user in a session or on sftp events

### ISSUE THREAD

**Issue by arthurvaverko-kaltura** [mscdex/ssh2#807]
I have authenticated a user with a 3rd party api .. and i have a token that i want to reuse once the user uploads a file

so im trying to figure out where can i get that toke from on a request for 
READDIR 
and 
OPEN
and 
READ
?

**Comment by mscdex** [comment]
I'm assuming you're implementing an SFTP server here, however SFTP is just SFTP. There is no provision for sending arbitrary opaque data in SFTP. You would probably have to enforce some process for the user to follow, like executing a certain command in order to pass the token. Otherwise you will have to get the token some other way, out of band/outside of SSH/SFTP.
