### ISSUE TITLE
Callback of forwardOut is never called if connection get disconnected

### ISSUE THREAD

**Issue by ztion** [mscdex/ssh2#814]
I have an SSH server using libssh2. And using forwardOut() on the Connection object to open a channel to the other side.

However, if the connection goes down ungracefully slightly before the forwardOut() call, the callback of forwardOut() is never called. I think the same should happen if the connection goes down gracefully after forwardOut() was able to send the channel open message, but never receives a reply.
The only thing you get is a 'end' event on the connection. I would prefer if you got a callback with an error in this case. It is possible to work around it for me, but it would be more convenient to get the callback with an error.

I guess this can be easiest reproduced by connecting to the SSH server from a client running in a VM. Then pause the VM, and then make your program do the forwardOut(). The callback is never called.

**Comment by mscdex** [comment]
I can't reproduce this with the latest version. We've had handling of outstanding requests on connection close for awhile now and I can't see any edge cases looking at the current code.

**Comment by perry-mitchell** [comment]
@mscdex I'm now seeing this error repeatedly on the latest version (0.8.9):

```
Error: connect ECONNREFUSED x.x.x.x:22
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/data/service/node_modules/ssh2/lib/client.js:307:10)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: 'x.x.x.x',
  port: 22,
  level: 'client-socket'
}
```

This causes a hard-crash of the application, which would have otherwise been handled gracefully if the callback had been executed.

This issue is intermittent and not possible to easily reproduce. Seems to be just some problem with our server, but of course the client shouldn't bail like this either.

**Comment by perry-mitchell** [comment]
Ok, I think I was able to resolve this by using a simple `.on("error" ...` handler:

```javascript
client
	.on("ready", () => {
		client.forwardOut(/* ... */);
	})
	.on("error", err => {
		// Reject surrounding promise, handle error etc.
	})
	.connect({ /* ... */ });
```

This *outer* error handler (not on the `forwardOut` call) is not documented in the readme, that I can see, so perhaps it might be useful to add it to some/all of the examples in the readme so that more people implement this handler? It seems necessary to catch the socket-level failures.
