### ISSUE TITLE
how to check if a remote directory or a file exists on sftp server

### ISSUE THREAD

**Issue by kishor1221** [mscdex/ssh2#823]
Could you please let me know how to check if a remote directory or a file exists on sftp server? does the client having any related helpful methods? will you be able to provide me the documentation of the same if any?

I tried something like this but not seems to be working as expected     // await sftp.exists(tempDirectoryName, (dirExistErr) => {
}

**Comment by mscdex** [comment]
As mentioned in the `ssh.sftp()` description in the readme, the documentation for methods available on the `sftp` object are available [here](https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md).

**Comment by dilin-MS** [comment]
So how to check if a remote directory exists? It seems no API in `sftp` has the function.
I would like to create remote directory if it does not exist. `sftp.readdir` does not meet my need since it can only check whether the directory exists in callback when error occurs. In this way the `mkdir` in `sftp.readdir` will be async.

Are there any sync way to check if a remote directory exists?
Thank you very much.
