### ISSUE TITLE
Can I get the host name from the tcpip-forward?

### ISSUE THREAD

**Issue by luukhoeben** [mscdex/ssh2#832]
Hey,

Sorry for bugging you again but I was wondering if there is a method or something to get the destination host and port from a `tcpip-forward`.

Like:
`ssh -R test:80:valet-domain.test:80 server.com`

Now I get the `test` and the first `80`, but I also want the `valet-domain.test` if that is possible so I can set the right host when making a request.

Is this possible?

**Comment by luukhoeben** [comment]
Oh and another thing, I always get this on every request I make (in the ssh client):
`setsockopt TCP_NODELAY: Invalid argument`

Is there something to fix that? :D

**Comment by luukhoeben** [comment]
@mscdex Is that even possible using this method?

**Comment by mscdex** [comment]
The syntax for the server->client tunneling (`-R`) that you're using is: `<server bind host>:<server bind port>:<client redirect host>:<client redirect port>`, so that means that 'valet-domain.test:80' is never transmitted to the server because it is only used locally to determine where to send incoming tunneled connections from the server.

This is why with `ssh2` as the client, you are able to set up remote forwards and handle them entirely within the same process if you wanted -- without needing any kind of client redirect host/port, because that information is not required to send to the server.

As far as the setsockopt error goes, if that's coming from the OpenSSH client, I can't really help you there.
