### ISSUE TITLE
Waht is SFTPWrapper?

### ISSUE THREAD

**Issue by robymes** [mscdex/ssh2#838]
sftp method callback doesn't return an SFTPStream object, but SFTPWrapper object
Is there any documentation for this object? in particular for readFile and writeFile methods

Thank you

**Comment by mscdex** [comment]
It's an object to be able to present an API that is identical to node's `fs` API. The `SFTPStream` can't be provided directly for this because it's a stream, so `.read()` and `.write()` would be stream methods and not the `fs` methods of the same name. That is the main reason for the wrapper. There is no documentation because the node `fs` documentation should be the documentation. The fact that a wrapper exists is an implementation detail.
