### ISSUE TITLE
How can you reliably determine the end of line?

### ISSUE THREAD

**Issue by coreyman** [mscdex/ssh2#845]
I tried testing for /r or /n every time the data stream comes back but I couldn't find either character in the output provided by debian over ssh. Testing the text values is a bit hard to do when you don't know if the stream has provided all the data back yet because the value could be a partial. I need to know how to reliably determine the end of the line so I can test the values in the line. I've tried so many different things but here is what I have now.

```

conn.shell(function(err, stream) {
  if (err) throw err;
    stream.on('close', function() {
      console.log('Stream :: close')
      conn.end();
    }).on('error', function(err, stream){
      throw err;
    }).on('data', function(data) {
      linePartial += data.toString();//lines come in as partials so we need to make sure we are getting a line ending
      //console.log(linePartial)
      line = null;
      if(/\r|\n/.exec(linePartial)){
        //console.log('we matched');
        line = linePartial
        linePartial = ''
      }
      if(!loggedIn){//begin login sequence
        //console.log('begin login sequence')
        if(!connected && !cmd1){
          //console.log('begin get inside vm')
          stream.write('virsh console testserialcomm_5d899d2b95ca\n')//first command issued after login so we get inside the vm
          cmd1 = true;//set this so we don't come back here
        }
        if((/Connected\sto\sdomain\s/i).test(line)){//we are connected to the virtual machine
```

**Comment by mscdex** [comment]
This kind of question is better asked on a place like stackoverflow.com or the [nodejs/help repo](https://github.com/nodejs/help/issues).

However, I will give you a few tips for the code snippet you've posted:

* You should use `stream.setEncoding('utf8')` **and** `linePartial += data` instead of just `linePartial += data.toString()` because if a multi-byte character gets split between data chunks, the character will be corrupted. Using `setEncoding()` prevents this and will pass (complete) strings instead of `Buffer`s to `'data'` events.

* There is no need to check for `'\r'` by itself since line endings should always have *at least* `'\n'`, so it's sufficient to just look for that character (and strip the preceding `'\r'` if it exists).

* You're not checking for the possibility of multiple lines existing in `linePartial`.

* The line parsing can be simplified by taking advantage of node's built-in `readline` module. For example:
    ```js
    const readline = require('readline');
    
    // ...
    
    client.shell((err, stream) => {
      if (err) throw err;
    
      stream.on('close', () => {
        console.log('Stream :: close')
        conn.end();
      });
    
      const rl = readline.createInterface({ input: stream });
      rl.on('line', (line) => {
        // Process stdout line here ...
        if (!loggedIn) {
          // ...
        }
      });
    
      // ...
    });
    ```
