### ISSUE TITLE
Explain "continue" event better

### ISSUE THREAD

**Issue by Timmmm** [mscdex/ssh2#868]
The documentation has this:

> continue() - Emitted when more requests/data can be sent to the server (after a Client method returned false).

Why does this event exist? And when do the `Client` methods return false? I couldn't find anything in the SSH2 RFCs about this. Is this just part of this API?

Also how do you even do this? The whole event API is awkward enough to use already due to splitting every event type into separate streams (rather than a single stream handling a tagged union which would be a lot easier!). None of the examples handle this `continue` event.

**Comment by mscdex** [comment]
The `'continue'` event exists because the client methods make requests to the server which means writing to the socket. If the socket buffer is full, node will begin to buffer the data in process memory. In this case the client method returns `false`, much like when writing to a node stream. The documentation shows this, for example for `exec()` (emphasis mine):

* exec(< _string_ >command[, < _object_ >options], < _function_ >callback) - _**boolean**_ - Executes `command` on the server. **Returns `false` if you should wait for the `continue` event before sending any more traffic.**

So when `false` is seen, you have the option of waiting for the socket buffer to clear before sending more requests if you don't want to use up process memory to temporarily store pending requests. If you want to do this, you would wait until the `'continue'` event is emitted.

> splitting every event type into separate streams (rather than a single stream handling a tagged union which would be a lot easier!)

I'm not sure what you mean by this. Can you explain a bit further?

**Comment by Timmmm** [comment]
Ah so it's optional. That explanation makes sense (and I think you could add it to the docs verbatim!).

> Can you explain a bit further?

Sure! So you've followed the idiomatic Javascript event callback API, i.e.

```
stream.on("data", (data) => {
  ...
});
stream.on("continue", () => {
  ...
});
```

Which is fine, but you kind of lose control flow context compared to something like this:

```
stream.addEventHandler((event) => {
   switch (event.type) {
      "data":
          ...
          break;
       "continue":
           ...
           break;
       }
    }
});
```

I guess it is not too difficult to wrap your API and turn it into mine. And given that it is optional, I think I can ignore it in my application.

**Comment by mscdex** [comment]
FWIW `EventEmitter` (which utilizes `.on()`/`.emit()`/etc.) is very much a node thing and used by everyone i've seen in the node community. Deviating from that would just cause confusion for node users.
