### ISSUE TITLE
Agent forwarding to ssh2.Server doesn't work

### ISSUE THREAD

**Issue by wbobeirne** [mscdex/ssh2#871]
Pardon me if I missed something obvious, but using `ssh2.Client` to connect to an `ssh2.Server` with the `agentForward` flag set doesn't seem to actually work. Is there something I'm failing to hook up, or is this just not a supported function of the server? Here's a simplified example of my code:

**client.ts**
```ts
ssh.on("ready", () => {
  ssh.exec("ssh-add -l", (err, stream) => {
    let errMsg = ""
    stream.stderr.on("data", data => {
      errMsg += data.toString()
    })
    stream.on("close", (code: number, signal: number) => {
      console.log(`Close with code ${code} and signal ${signal}`)
    })
  })
}).connect({
  username: "username",
  password: "password",
  agent: process.env.SSH_AUTH_SOCK,
  agentForward: !!process.env.SSH_AUTH_SOCK,
})
```

**server.ts**
```ts
const hostKey = fs.readFileSync(hostKeyPath)
this.sshServer = new ssh.Server({ hostKeys: [hostKey] }, (client, info) => {
  client.on("authentication", ctx => ctx.accept())
  client.on("session", (accept) => {
    const session = accept()
    session.on("auth-agent", (accept) => {
      accept()
    })
  })
})
```

Ends up having the client print:
```
Exited with code 2: Could not open a connection to your authentication agent.
```

`SSH_AUTH_SOCK` is also unset in that session (I tried echoing it as my command instead)

**Comment by mscdex** [comment]
The `ssh2.Server` does not set up UNIX sockets or set environment variables for commands when agent forwarding is enabled for a client because how commands are executed is up to the end user/implementer. So to emulate what OpenSSH does, you'd need to set up a `net.createServer()` (which pipes incoming sockets to the client (using `openssh_authAgent()`) and vice versa) for the client, listening on a path and setting any environment variables on client `exec()`/shell()` appropriately.
