### ISSUE TITLE
SSH2 hangs after connected event in node10.x

### ISSUE THREAD

**Issue by yadavsahil197** [mscdex/ssh2#872]
We are using the **tunnel-ssh** library to setup local port forwarding from a bastion host. The port forwarding works fine most of the times but hangs after the below event once in a while. (node version - 8.10, ssh2 - 0.8.7)

DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.8'
DEBUG: Client: Trying *.*.*.* on port 22 ...
DEBUG: Client: Connected

The above issue seems to occur much more frequently when we moved to node 10. We had observed issues with stream handling after moving to node 10 at other places as well in our code. Specifically, it was the change in how the readable event should be handled from node 8 to node 10. Are the above two issues related? Thanks!

**Comment by mscdex** [comment]
I have no idea. If there is a way I can duplicate the issue on my end I can look into it.

**Comment by yadavsahil197** [comment]
It is occurring in our prod environment and we are not able to reproduce the issue in dev environment. So it could also be something related to bastion host config.
But I added some more debug logs inside ssh2 Client as well as ssh2-streams ssh. What's happening is, inside ssh2 client, we receive the socket **connect** event, but immediately after, we get a socket **end** event  which thereby closes the ssh2 stream. Therefore there are no more debug logs. Do you know why thee socket is getting closed immediately after connection?

**Comment by mscdex** [comment]
Are you performing connection hopping of any kind or just connecting to a single ssh server and forwarding from there?

**Comment by yadavsahil197** [comment]
We perform a local port forwarding, we ssh to the bastion host and then to the destination (RDS instance).

**Comment by mscdex** [comment]
Which leg is the issue occurring with? The first host or the second host?

**Comment by yadavsahil197** [comment]
It is on the first host. This is the code that is being used https://github.com/agebrock/tunnel-ssh/blob/master/index.js.
We do not receive the ready event which is emitted once the ssh auth is completed. https://github.com/agebrock/tunnel-ssh/blob/f88fc8ea6de3156806e272ecf7326aad54ff1a77/index.js#L13

**Comment by mscdex** [comment]
If it's the initial host then I don't know why there would be any problem as long as there's nothing wrong with the host.

Out of curiosity, is there any change in behavior with node v12.x and/or v13.x?

**Comment by yadavsahil197** [comment]
The more worrying part is that it happens sporadically and the frequency increased multi-folds after node10 update. 
With node12 also the behaviour is same. Haven't tried with node 13. 
If it helps, the port forwarding happens through a lambda while the bastion host and rds are in a separate VPC.

**Comment by yadavsahil197** [comment]
Also, there are several such lambdas that set up port forwarding at a given time, run some queries on rds and closes the connection.
I was wondering if it can hit the limit of open file descriptors on bastion from a given IP. But then again, the behaviour should not change from node 8 to node 10

**Comment by theophilusx** [comment]
Just FYI we had similar issues when we moved from node v8 to node v10. Our setup was much simpler (no port forwarding - just sftp). We identified two contributing factors. One we were able to resolve, the other we were able to work-around. 

The first was due to attempting to establish too many ssh connections too fast. The remote system had a limit of 10 unauthenticated SSH connections. After reaching 10, it would begin to randomly drop/close a percentage of unauthenticated connections until a hard limit of 15 or 20 (can't remember the actual number) at which time, it would then refuse all connections. We did not realize this was impacting us because we are making authenticated connections (username/password), but then we realized that any connection initially goes through an unauthenticated period prior to establishing handshake, key exchange etc.  The key symptom here was what appeared to be sporadic connection closed by peer errors. We modified our code to re-use connections (thus requiring less) and put some code in place to make sure we didn't try to make more than 10 connections in a very short period which appears to have fixed this issue.

The other issue we had was with compression. This only happened in our prod environment and only with connections that passed through our Palo Alto firewall. The symptom was that the connection would just appear to hang - no error, end or close signals seen - the transfer (download - get or fastget) would just hang. Setting compression to 'off' fixed this issue for us. It is my guess that something in the Palo Alto deep packet inspection was being tripped. The remote connection would be established and the transfer would begin, but then the firewall would just start blocking packets and everything would hang. This was specific to node v10 and later. In node v8.x there was no issue (though to be honest, we also saw no real performance difference with compression set to on, off or auto, so maybe it was never 'on' in node v8.x. 

One reason I believe this was Pal alto specific is that testing the exact same code with the same remote end point, but on a network which did not pass through the firewall worked fine. so if not the firwall, it does seem to be something specific to that network. 

This was all from about 12 months ago and may not be relevant with newer versions of ssh2 or node.

**Comment by mscdex** [comment]
Thanks for the detailed information @theophilusx !

**Comment by yadavsahil197** [comment]
Thanks a lot for the super helpful info @theophilusx . The first one was definitely a contributing factor in our case. I need to check whether turning off the compression helps.
For a temporary workaround, we are catching errors if the socket was closed by the bastion server before handshake was complete. When that happens, we retry after exponential backoff.
But for scalability, we need to utilise something like [serverless-mysql].(https://github.com/jeremydaly/serverless-mysql).
