### ISSUE TITLE
(bug) exec fails to execute command (127 error code)

### ISSUE THREAD

**Issue by asafmas-rnd** [mscdex/ssh2#888]
Hi,
i'm trying to activate remote google earth enterprise (on Ubuntu virtual machine) commands via ssh2

when running simple ls -lh command via the ss2 all is well but when running the google earth command i get 127 error code

![image](https://user-images.githubusercontent.com/45232590/79985178-e63ca280-84b2-11ea-9323-b0d62cb52711.png)

the same command works fine manually from my **local** machine via putty or cmd and affects the remote (VM) machine as expected
![image](https://user-images.githubusercontent.com/45232590/79986605-fbb2cc00-84b4-11ea-804c-47cde239028a.png)

what am i doing wrong?
what can i do to make it work?

Thanks.

The code i'm using:
var Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', function() {
  console.log('Client :: ready');
//   conn.exec('ls -lh', function(err, stream) {
  conn.exec('genewmapdatabase --help', function(err, stream) {
    if (err) throw err;
    stream.on('close', function(code, signal) {
      console.log('Stream :: close :: code: ' + code + ', signal: ' + signal);
      conn.end();
    }).on('data', function(data) {
      console.log('STDOUT: ' + data);
    }).stderr.on('data', function(data) {
      console.log('STDERR: ' + data);
    });
  });
}).connect({
  host: 'localhost',
  port: 30022, (forward to port 22 on my VM)
  username: 'xxx',
  password: 'xxx'
});

**Comment by mofux** [comment]
So if you run `genewmapdatabase --help` and then directly after `echo $?` locally, what is the output of the last command? I expect it to be 127.

**Comment by asafmas-rnd** [comment]
Thanks for the fast reply, do you mean something like this?
![image](https://user-images.githubusercontent.com/45232590/79991375-ef317200-84ba-11ea-877d-740acde421e5.png)
it's working from my local machine

**Comment by mscdex** [comment]
An exit code of 127 means bash couldn't find the command. My guess is that there is something in the login user's shell session initialization script that is changing the `PATH` environment variable such that the `genewmapdatabase` command is found.

You can verify this a few different ways:

* By comparing the result of `echo $PATH` from `ssh2` and from your interactive shell session immediately after logging in.

* Executing the same `genewmapdatabase --help` command via the OpenSSH client using the same command execution mechanism that `ssh2` is using (via `.exec()`) by supplying the command on the command line, for example: `ssh user@localhost -p 30022 'genewmapdatabase --help'` (which should result in the same error you get from `ssh2`).

* Executing the command in an interactive shell via `conn.shell()` -- this is merely for testing and not a real solution since it's harder to parse command output this way and you don't get exit codes/signals for individual commands.

**Comment by asafMasa** [comment]
ok i see what you meen:
![image](https://user-images.githubusercontent.com/18442671/80384239-4cf3fe80-88ad-11ea-9fb2-1c9d90139f43.png)

the opt/google/bin doesn't exist when printing from the ssh2
![image](https://user-images.githubusercontent.com/18442671/80384389-7e6cca00-88ad-11ea-9717-9f408bd04a48.png)

why? how can i add it?
