### ISSUE TITLE
Dynamic (1:1) port forwarding with ssh client and node-ssh2 server

### ISSUE THREAD

**Issue by sidorares** [mscdex/ssh2#896]
I guess it might be more a question about ssh client rather than this library. 

I'm trying to create a tunnel functionality within my service and wonder if its possible to use standard `ssh` command line client so that I don't need to distribute any special tunnel to users.

This is kind of reverse to [socks](https://github.com/mscdex/ssh2#dynamic-11-port-forwarding-using-a-socksv5-proxy-using-socksv5) example: I want my service to route outgoing connections via client ssh stream. Forcing users to enter full list of possible outgoing connections is probably ok restriction ( but would be good to be able to have this fully dynamic ): `ssh -R 1234:allowedserver1:80 -R 1235:allowedserver2:80 tunnelserver`

**Comment by mscdex** [comment]
I'm not quite sure what you're asking. `-R ...` will forward connections on the server to the client, but it sounds like you want `-L ...` instead, which forwards connections on the client to the server?

**Comment by sidorares** [comment]
I'm running headless chrome on box A and intercept all networking in chrome. I want proxy those networking to box B. "B" is a client ( possibly behind nat/firewall , does not run ssh server but can connect ssh client to A. I want "destIp,destAddr" packets go from server A to B's ssh client connection, and then go to `destIp,destAddr` from B

**Comment by mscdex** [comment]
One solution could be to implement a custom ssh subsystem for transferring the packets, but you'd have to design your own protocol around it because a custom subsystem would just present you with a raw duplex stream of bytes. Server-wise you should be able to accomplish this with `ssh2` or OpenSSH, but client-wise you'd probably use `ssh2`.

Be aware if you use this method, it will use up a channel each time, so if you are using OpenSSH as the server there is a default limit of 10 (I think) channels at any given time per connection. To avoid having to change that configuration you could try to multiplex data from multiple connections over the same channel, which would complicate your custom protocol however.

**Comment by mscdex** [comment]
Additionally, the OpenSSH client supports reverse dynamic forwarding since 7.6. So you could set a SOCKS proxy for the browser and point it at the SOCKS proxy, which should transfer the connections back over to the client, just like a normal reverse port forward.

**Comment by sidorares** [comment]
Thanks for suggestions @mscdex , I was hoping that I can use standard openssh `ssh` command on client machine, looks like it's not possible
