### ISSUE TITLE
handle object not equal

### ISSUE THREAD

**Issue by AlexandraK** [mscdex/ssh2#913]
The handle object that is passed in stream events is not equal to the initial handle object .

Example
```

let handles = new Map(),
     handleIndex = 0;

stream.on('OPENDIR', (reqid, path) => {
    const handle = new Buffer(4);
    handle.writeUInt32BE(handleIndex, 0, true);
    handles.set(handle, {path});
    handleIndex++;
    return stream.handle(reqid, handle);
});

stream.on('READDIR', (reqid, handle) => {
    if(!handles.has(handle)
       console.log('no such handle');
    ....
});
```

The `handle.has` does not recognize the same handle object because the object is different.

**Comment by mscdex** [comment]
`map.has()` compares values like `hasArgument === storedValue`. So for objects that means it's comparing references and not the values stored in them. You can verify this by adding `console.log(handles.has(handle));` in your `'OPENDIR'` handler. Since it's the same reference it will return `true`.

`ssh2` does not have its own `Map` or similar in-memory storage for retaining handle values/references because that would be duplicating work and would reduce flexibility. All `ssh2` does is parse the binary value from the client and pass it on to the user (as a `Buffer` instance). So you will either need a different/custom data structure that takes object values into account somehow, or just use the integer value (`handleIndex`) as the key instead. For the latter case you can then inside your `'READDIR'` handler, check that `handle.length === 4` and that the integer value stored within (using `readUInt32BE(0)`) is something that exists in your map.

Also on an unrelated note, `new Buffer()` is deprecated in node, so you should probably switch to `Buffer.alloc()`/`Buffer.allocUnsafe()`.

**Comment by AlexandraK** [comment]
Hi,

yes that was what I meant, that references aren't equal.

anyway I created a custom class for this, but I think it's inefficient and I think ssh2 should just pass the same object around. I don't understand why it has to look into the contents. Or just use some integer index instead of buffer.


```

class HandleMap{

  constructor(){
    this.map = {};
    this.nextIndex = 0;
  }

  create(data){
    const handle = Buffer.alloc(4);
    handle.writeUInt32BE(this.nextIndex, 0, true);

    this.map[this.nextIndex] = data;
    this.nextIndex++;
    return handle;
  }

  has(handle){
    if(handle.length !== 4)
      return false;

    const index = handle.readUInt32BE(0, true);
    return this.map.hasOwnProperty(index);
  }

  get(handle){
    if(handle.length !== 4)
      return false;

    const index = handle.readUInt32BE(0, true);
    if(!this.map.hasOwnProperty(index))
      return false;

    return this.map[index];
  }

  set(handle, data){
    const index = handle.readUInt32BE(0, true);
    this.map[index] = data;
  }

  delete(handle){
    const index = handle.readUInt32BE(0, true);
    if(this.map.hasOwnProperty(index))    
      delete this.map[index];
  }

}


```

**Comment by mscdex** [comment]
> I think ssh2 should just pass the same object around.

This isn't really possible because `ssh2` would have the same issue as you're having. It would not only have to store handle references, but it would *also* need to devise some way of interpreting the contents of each handle to use as a key for looking up the correct handle reference when a READDIR request comes in for example. This not only adds additional overhead but it's also not efficient and shouldn't be making this kind of design decision for the user.

> I don't understand why it has to look into the contents. Or just use some integer index instead of buffer.

As with any binary protocol, when `ssh2` receives a READDIR request for example, it just sees bytes of data. Since handles are meant to be treated as opaque blobs of data (they could be anything -- a 32-bit integer, a 64-bit integer, a string, a `BigInt`, etc.), `ssh2` just leaves this binary data as-is in a `Buffer` instance and passes that on to the user so they can interpret that data however they want.

As far as why you have to use a primitive value (e.g. number, string, boolean, etc.) instead of an object (e.g. literals like `{ foo: 'bar' }`, anything created with the `new` keyword, etc.) to have things like `map.has()` work, I've already explained that. Objects are compared by reference (think pointer if you're familiar with lower level languages like C/C++) and not by value. By using the integer value (which you are storing inside the handle), you are allowing the comparison used by V8 in `map.has()` to work as expected since numbers are primitive values in JavaScript.

> Why does it have to be a 4 byte buffer if it only stores a integer value?

The handle doesn't *have to be* a 4 byte value. If you're referring to my previous comment about checking the handle length, that was just because you were creating a 4-byte `Buffer` handle and writing a 32-bit integer to it (which takes up the entire 4 bytes), so naturally the client should be expected to send exactly 4 bytes every time for handles.

**Comment by AlexandraK** [comment]
so you are saying that this handle buffer is required because it is sent to the client, and the client sends it back later and that's why the server looses the reference to it and creates a new one from what the client sends?
Is the buffer required by the protocol? Because to me that buffer seems useless to the client and it just complicates things. Server can just identify a "handle" by a number, so there wouldn't be any need for parsing

**Comment by mscdex** [comment]
> so you are saying that this handle buffer is required because it is sent to the client, and the client sends it back later and that's why the server looses the reference to it and creates a new one from what the client sends?

Correct.

> Is the buffer required by the protocol?

`Buffer` objects are used in node to easily pass around raw, binary data (like a `Uint8Array` object for example). The protocol itself doesn't care about `Buffer`s or anything language-specific, it just deals with binary data. However, `ssh2` needs some way to pass these opaque handles as-is to the other end, so it uses `Buffer`s to accomplish that.

The client may not even be written in node/JavaScript, so it will store the opaque handle in whichever way it sees fit.

> Server can just identify a "handle" by a number, so there wouldn't be any need for parsing

There will always have to be some kind of parsing/interpreting of the binary data in the handle. Whether it's done explicitly by you or implicitly by the author of some special Map-like data structure that instead compares `Buffer`s by value instead of reference.

For example, the way OpenSSH creates handles for opened files (the last I checked) is they use a 4-byte value that literally contains the 32-bit file descriptor number. However like I said, since handles are opaque, you could even have the handle be the string "hello world" if you wanted -- as long as you understood that when the client sends back that same string handle.

**Comment by AlexandraK** [comment]
ok, thanks for the explanation
