### ISSUE TITLE
Timed out while waiting for handshake - AWS Lambda Node.js 12.x

### ISSUE THREAD

**Issue by CodeZeno** [mscdex/ssh2#922]
I am doing something similar to the below for about 15 files.

```JavaScript
//Simplified for brevity
const sftpClient = require('ssh2').Client;
const files = ["one","two","three"];
for (const content of files) {
  let filename = content+".txt";
  let id = "file_"+content;
  let sftpConnection = new sftpClient();
  sftpConnection.on('ready', function() {
    sftpConnection.sftp(function(err, sftp) {
      if (err) {
        console.log("Could not connect to SFTP server", err);
      } else {
        sftp.writeFile('/mypath/'+filename, content, function(err) {
          if (err) {
            console.log("Could not create file "+filename, err);
          } else {
            console.log("Created "+filename);
            removeProcessed(id);//remove a record from a DynamoDB table
          }
          sftpConnection.end();
        });
      }
    });
  }).connect({
    host: 'my.host.com.au',
    port: 22,
    username: 'myusername',
    password: 'mypassword',
    readyTimeout: 99999
  });
}
```

I receive the following error after processing around 3-5 files:

Uncaught Exception 	
```
{
    "errorType": "Error",
    "errorMessage": "Timed out while waiting for handshake",
    "level": "client-timeout",
    "stack": [
        "Error: Timed out while waiting for handshake",
        "    at Timeout._onTimeout (/var/task/node_modules/ssh2/lib/client.js:695:19)",
        "    at listOnTimeout (internal/timers.js:549:17)",
        "    at processTimers (internal/timers.js:492:7)"
    ]
}
```

1. What causes this and what can be done to avoid it?
2. How do I capture/handle this error?
3. Is there a way to reuse the connection to upload multiple files? When I tried it seemed to fall over if I didn't close the connection after writing a file.

Running on Node.js 12.x in AWS Lambda with 256MB memory and a 5min timeout.
Function runs for about 20 seconds successfully and then nothing happens for then next 90 seconds and then the error shows up.

**Comment by mscdex** [comment]
1. I believe it was OpenSSL 1.1.0 or 1.1.1 that introduced some changes that made some crypto operations take substantially longer. However, with node v14.x, `ssh2` supports additional algorithms (specifically curve25519) which if used during a connection, it should resolve connection timeout issues since it is a different type of algorithm than the diffie-hellman ones.

2. Add an `'error'` event handler on the connection object

3. Reusing the connection is always ideal where possible. Be aware however that in this case that would also include reusing the same sftp session (this means sharing the `sftp` from the `.sftp()` callback). The reason for that is that sftp sessions take up separate channels and most servers place limits on the number of simultaneous open channels per connection. However reusing the same sftp session is fine because I've never seen a server limit the number of outstanding sftp requests.

**Comment by CodeZeno** [comment]
Thank you for the help.
It seemed the issue was that the remote end did not like so many connections.
I was able to adjust my code so that a single sftp was available to my functions.
I have not had this problem since.

```JavaScript
const sftpClient = require('ssh2').Client;
const sftpConnection = new sftpClient();
let sftp;

sftpConnection
.on('ready', function() {
  sftpConnection.sftp(function(err, connection) {
    if (err) throw (err);
    sftp = connection;
    doSomething()
    .then(function(){
      sftpConnection.end();
    })
    .catch(function(err){
      console.error(err);
    });
  });
})
.on('error', console.error)
.connect({
  host: 'my.host.com.au',
  port: 22,
  username: 'myusername',
  password: 'mypassword',
  readyTimeout: 99999
});

function doSomething() {
  return new Promise((resolve, reject) => {
    const files = ["one","two","three"];
    for (const content of files) {
      let filename = content+".txt";
      let id = "file_"+content;
      sftp.writeFile('/mypath/'+filename, content, function(err) {
        if (err) throw (err);
        console.log("Created "+filename);
      });
    };
    resolve();
  });
}
```

**Comment by justinmchase** [comment]
I only have a single connection and am also encountering this on lambda v12
